<?php

########################################################################
# Extension Manager/Repository config file for ext: "css_select"
#
# Auto generated 04-04-2008 00:52
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Page StyleSheet Selector',
	'description' => 'Select one or more stylesheet(s) for each page of the tree... The goal of this extension is to drastically reduce the weight of the pages generated by TYPO3, by including only the styles needed in the page.',
	'category' => 'be',
	'shy' => 0,
	'dependencies' => '',
	'conflicts' => '',
	'priority' => '',
	'loadOrder' => '',
	'module' => '',
	'state' => 'stable',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => 'pages',
	'clearCacheOnLoad' => 1,
	'lockType' => '',
	'author' => 'Jean-David Gadina',
	'author_email' => 'macmade@gadlab.net',
	'author_company' => 'macmade.net',
	'CGLcompliance' => '',
	'CGLcompliance_note' => '',
	'version' => '0.5.0',
	'constraints' => array(
		'depends' => array(
			'php' => '5.2.0-0.0.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
	'_md5_values_when_last_written' => 'a:13:{s:20:"class.ext_update.php";s:4:"8642";s:40:"class.tx_cssselect_handlestylesheets.php";s:4:"380a";s:21:"ext_conf_template.txt";s:4:"1a18";s:12:"ext_icon.gif";s:4:"c839";s:17:"ext_localconf.php";s:4:"444a";s:14:"ext_tables.php";s:4:"3ac4";s:14:"ext_tables.sql";s:4:"e549";s:16:"locallang_db.xml";s:4:"aa7e";s:14:"doc/manual.sxw";s:4:"0ce2";s:30:"pi1/class.tx_cssselect_pi1.php";s:4:"fb15";s:11:"res/css.gif";s:4:"afab";s:20:"static/constants.txt";s:4:"1311";s:16:"static/setup.txt";s:4:"b59b";}',
	'suggests' => array(
	),
);

?>