TYPO3OOP: tx_oop_Xhtml_Comment Class Reference
tx_oop_Xhtml_Comment Class Reference
Public Member Functions
__construct ($text)
__toString ()
__set ($name, $value)
__get ($name)
__call ($name, array $args=array())
offsetExists ($offset)
offsetGet ($offset)
offsetSet ($offset, $value)
offsetUnset ($offset)
rewind ()
current ()
key ()
next ()
valid ()
addChildNode (tx_oop_Xhtml_Tag $child)
addTextData ($data)
asHtml ()
asXml ()
getParent ($parentIndex=0)
Static Public Member Functions
static useFormattedOutput ($value)
Protected Member Functions
_output ($xmlCompliant=false, $level=0)
_addSpacer ($pixels)
_addComment ($text)
_addChild ($name)
Protected Attributes
$_comment = ''
$_tagName = ''
$_attribs = array()
$_children = array()
$_childrenByName = array()
$_childrenCountByName = array()
$_childrenCount = 0
$_hasNodeChildren = false
$_parents = array()
$_iteratorIndex = 0
Static Protected Attributes
static $_formattedOutput = true
static $_hasStatic = false
static $_emptyTags
static $_NL = ''
static $_TAB = ''
Detailed Description
Definition at line 38 of file Comment.class.php.
Constructor & Destructor Documentation
tx_oop_Xhtml_Comment::__construct ($ text)
Class constructor
Returns:
NULL
See also:
tx_oop_Xhtml_Tag::__construct
Reimplemented from tx_oop_Xhtml_Tag.
Definition at line 51 of file Comment.class.php.
Member Function Documentation
tx_oop_Xhtml_Comment::_output ($ xmlCompliant = false, $ level = 0) [protected]
Returns the HTML comment
Parameters:
boolean Wheter the output must be XML compliant
int The indentation level
Returns:
string The HTML comment, if $xmlCompliant is false, otherwise a blank string
Reimplemented from tx_oop_Xhtml_Tag.
Definition at line 67 of file Comment.class.php.
tx_oop_Xhtml_Tag::__toString () [inherited]
Definition at line 140 of file Tag.class.php.
References tx_oop_Xhtml_Tag::asHtml().
tx_oop_Xhtml_Tag::__set ($ name, $ value) [inherited]
Definition at line 148 of file Tag.class.php.
References tx_oop_Xhtml_Tag::_addChild().
tx_oop_Xhtml_Tag::__get ($ name) [inherited]
Definition at line 156 of file Tag.class.php.
References tx_oop_Xhtml_Tag::_addChild().
tx_oop_Xhtml_Tag::__call ($ name, array $ args = array()) [inherited]
Definition at line 164 of file Tag.class.php.
References tx_oop_Xhtml_Tag::_addComment(), and tx_oop_Xhtml_Tag::_addSpacer().
tx_oop_Xhtml_Tag::offsetExists ($ offset) [inherited]
Definition at line 183 of file Tag.class.php.
tx_oop_Xhtml_Tag::offsetGet ($ offset) [inherited]
Definition at line 191 of file Tag.class.php.
tx_oop_Xhtml_Tag::offsetSet ($ offset, $ value) [inherited]
Definition at line 199 of file Tag.class.php.
tx_oop_Xhtml_Tag::offsetUnset ($ offset) [inherited]
Definition at line 207 of file Tag.class.php.
tx_oop_Xhtml_Tag::rewind () [inherited]
Moves the position to the first tag (SPL Iterator method)
Returns:
NULL
Definition at line 217 of file Tag.class.php.
tx_oop_Xhtml_Tag::current () [inherited]
Returns the current tag (SPL Iterator method)
Returns:
tx_oop_Xhtml_Tag The current HTML tag object
Definition at line 227 of file Tag.class.php.
tx_oop_Xhtml_Tag::key () [inherited]
Gets the tag name for the current tag (SPL Iterator method)
Returns:
int The name of the current tag
Definition at line 237 of file Tag.class.php.
tx_oop_Xhtml_Tag::next () [inherited]
Moves the position to the next tag (SPL Iterator method)
Returns:
NULL
Definition at line 247 of file Tag.class.php.
tx_oop_Xhtml_Tag::valid () [inherited]
Checks for a current tag (SPL Iterator method)
Returns:
boolean
Definition at line 257 of file Tag.class.php.
static tx_oop_Xhtml_Tag::useFormattedOutput ($ value) [static, inherited]
Definition at line 282 of file Tag.class.php.
tx_oop_Xhtml_Tag::_addSpacer ($ pixels) [protected, inherited]
Definition at line 293 of file Tag.class.php.
References tx_oop_Xhtml_Tag::_addChild().
Referenced by tx_oop_Xhtml_Tag::__call().
tx_oop_Xhtml_Tag::_addComment ($ text) [protected, inherited]
Definition at line 304 of file Tag.class.php.
Referenced by tx_oop_Xhtml_Tag::__call().
tx_oop_Xhtml_Tag::_addChild ($ name) [protected, inherited]
Definition at line 329 of file Tag.class.php.
Referenced by tx_oop_Xhtml_Tag::__get(), tx_oop_Xhtml_Tag::__set(), and tx_oop_Xhtml_Tag::_addSpacer().
tx_oop_Xhtml_Tag::addChildNode (tx_oop_Xhtml_Tag $ child) [inherited]
Definition at line 439 of file Tag.class.php.
Referenced by tx_oop_Xhtml_Tag::addTextData().
tx_oop_Xhtml_Tag::addTextData ($ data) [inherited]
Definition at line 468 of file Tag.class.php.
References tx_oop_Xhtml_Tag::addChildNode().
tx_oop_Xhtml_Tag::asHtml () [inherited]
Definition at line 487 of file Tag.class.php.
References tx_oop_Xhtml_Tag::_output().
Referenced by tx_oop_Xhtml_Tag::__toString().
tx_oop_Xhtml_Tag::asXml () [inherited]
Definition at line 495 of file Tag.class.php.
References tx_oop_Xhtml_Tag::_output().
tx_oop_Xhtml_Tag::getParent ($ parentIndex = 0) [inherited]
Definition at line 503 of file Tag.class.php.
Field Documentation
tx_oop_Xhtml_Comment::$_comment = '' [protected]
The text of the comment
Definition at line 43 of file Comment.class.php.
tx_oop_Xhtml_Tag::$_formattedOutput = true [static, protected, inherited]
Wether the output is formatted or not
Definition at line 43 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_hasStatic = false [static, protected, inherited]
Wether the static variables are set or not
Definition at line 48 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_emptyTags [static, protected, inherited]
Initial value:
 array(
        'area'  => true,
        'base'  => true,
        'br'    => true,
        'col'   => true,
        'img'   => true,
        'input' => true,
        'hr'    => true,
        'link'  => true,
        'meta'  => true,
        'param' => true
    )
The list of the XHTML empty tags (as in the XHTML 1.0 Strict DTD)
Definition at line 53 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_NL = '' [static, protected, inherited]
The new line character
Definition at line 69 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_TAB = '' [static, protected, inherited]
The tabulation character
Definition at line 74 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_tagName = '' [protected, inherited]
The name of the current tag
Definition at line 79 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_attribs = array() [protected, inherited]
The attributes of the current tag
Definition at line 84 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_children = array() [protected, inherited]
Definition at line 89 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_childrenByName = array() [protected, inherited]
Definition at line 94 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_childrenCountByName = array() [protected, inherited]
Definition at line 99 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_childrenCount = 0 [protected, inherited]
Definition at line 104 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_hasNodeChildren = false [protected, inherited]
Definition at line 109 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_parents = array() [protected, inherited]
Definition at line 114 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_iteratorIndex = 0 [protected, inherited]
The current position for the SPL Iterator methods
Definition at line 119 of file Tag.class.php.
The documentation for this class was generated from the following file:
tx/oop/Xhtml/Comment.class.php