<?php
	/**
	 * Language labels for database tables/fields belonging to extension 'weblinks'
	 *
	 * This file is detected by the translation tool.
	 */
	$LOCAL_LANG = Array (
		'default' => Array (
			'tx_weblinks_categories' => 'Web link category',
			'tx_weblinks_categories.title' => 'Title',
			'tx_weblinks_categories.parent' => 'Parent category',
			'tx_weblinks_categories.parent.I.0' => 'None',
			'tx_weblinks_categories.incharge' => 'Person(s) in charge (for dead links reports)',
			'tx_weblinks_links' => 'Web link',
			'tx_weblinks_links.s_link' => 'Link',
			'tx_weblinks_links.s_infos' => 'Infos',
			'tx_weblinks_links.s_special' => 'Special',
			'tx_weblinks_links.title' => 'Title',
			'tx_weblinks_links.category' => 'Category',
			'tx_weblinks_links.url' => 'URL',
			'tx_weblinks_links.bug' => 'Link reported inaccessible',
			'tx_weblinks_links.target.I.0' => '_blank',
			'tx_weblinks_links.target.I.1' => '_self',
			'tx_weblinks_links.target.I.2' => '_parent',
			'tx_weblinks_links.target.I.3' => '_top',
			'tx_weblinks_links.target' => 'Target',
			'tx_weblinks_links.description' => 'Description',
			'tx_weblinks_links.picture' => 'Picture',
			'tt_content.flexform_pi1.s_def' => 'Main',
			'tt_content.flexform_pi1.s_cat' => 'Category settings',
			'tt_content.flexform_pi1.s_cat.expand_levels' => 'Number of levels to expand',
			'tt_content.flexform_pi1.s_list' => 'List settings',
			'tt_content.flexform_pi1.s_list.sort_by' => 'Default sort by instruction',
			'tt_content.flexform_pi1.s_list.max_records' => 'Maximum number of items to display on a page',
			'tt_content.flexform_pi1.s_list.max_pages' => 'Maximum number of pages to display in the browse box',
			'tt_content.flexform_pi1.s_tmpl' => 'Template settings',
			'tt_content.flexform_pi1.s_tmpl.template_file' => 'Template file',
			'tt_content.list_type_pi1' => 'Web links',
		),
		'fr' => Array (
			'tx_weblinks_categories' => 'Catégorie de lien web',
			'tx_weblinks_categories.title' => 'Titre',
			'tx_weblinks_categories.parent' => 'Catégorie parente',
			'tx_weblinks_categories.parent.I.0' => 'Aucune',
			'tx_weblinks_categories.incharge' => 'Responsable(s) (pour le signalement des liens morts)',
			'tx_weblinks_links' => 'Lien web',
			'tx_weblinks_links.s_link' => 'Lien',
			'tx_weblinks_links.s_infos' => 'Infos',
			'tx_weblinks_links.s_special' => 'Spécial',
			'tx_weblinks_links.title' => 'Titre',
			'tx_weblinks_links.category' => 'Catégorie',
			'tx_weblinks_links.url' => 'URL',
			'tx_weblinks_links.bug' => 'lien signalé inaccessible',
			'tx_weblinks_links.target.I.0' => '_blank',
			'tx_weblinks_links.target.I.1' => '_self',
			'tx_weblinks_links.target.I.2' => '_parent',
			'tx_weblinks_links.target.I.3' => '_top',
			'tx_weblinks_links.target' => 'Cible',
			'tx_weblinks_links.description' => 'Description',
			'tx_weblinks_links.picture' => 'Image',
			'tt_content.flexform_pi1.s_def' => 'Principal',
			'tt_content.flexform_pi1.s_cat' => 'Paramètres des catégories',
			'tt_content.flexform_pi1.s_cat.expand_levels' => 'Nombre de niveau à afficher',
			'tt_content.flexform_pi1.s_list' => 'Paramètres de liste',
			'tt_content.flexform_pi1.s_list.sort_by' => 'Classement par défaut',
			'tt_content.flexform_pi1.s_list.max_records' => 'Nombre maximum de recherches à afficher sur une page',
			'tt_content.flexform_pi1.s_list.max_pages' => 'Nombre maximum de pages à afficher dans la boîte de navigation',
			'tt_content.flexform_pi1.s_tmpl' => 'Paramètres de gabarit',
			'tt_content.flexform_pi1.s_tmpl.template_file' => 'Gabarit',
			'tt_content.list_type_pi1' => 'Annuaire web',
		),
	);
?>
