<?php
	/**
	 * Language labels for database tables/fields belonging to extension "weleda_sport"
	 *
	 * This file is detected by the translation tool.
	 */
	$LOCAL_LANG = Array (
		'default' => Array (
			'tt_content.list_type_pi1' => 'Weleda Sport',
			'tx_weledasport_cat' => 'Weleda - Category',
			'tx_weledasport_cat.name' => 'Name',
			'tx_weledasport_cat.season' => 'Season',
			'tx_weledasport_cat.season.I.0' => 'Winter',
			'tx_weledasport_cat.season.I.1' => 'Summer',
			'tx_weledasport_sportsmen' => 'Weleda - Sportsman',
			'tx_weledasport_sportsmen.name' => 'Name',
			'tx_weledasport_sportsmen.car' => 'Category',
			'tx_weledasport_sportsmen.link' => 'Website',
			'tx_weledasport_sportsmen.description' => 'Description',
			'tx_weledasport_sportsmen.palmares' => 'Palmares',
			'tx_weledasport_sportsmen.palmares.section' => 'Add a new palmares',
			'tx_weledasport_sportsmen.palmares.text' => 'Text',
			'tx_weledasport_sportsmen.advice' => 'Advice',
			'tx_weledasport_sportsmen.product' => 'About product',
			'tx_weledasport_sportsmen.picture' => 'Picture',
			'tx_weledasport_sportsmen.thumbnail' => 'Thumbnail',
			'tt_content.flexform_pi1.s_def' => 'Main',
			'tt_content.flexform_pi1.s_flash' => 'Flash settings',
			'tt_content.flexform_pi1.s_flash.version' => 'Version',
			'tt_content.flexform_pi1.s_flash.width' => 'Width',
			'tt_content.flexform_pi1.s_flash.height' => 'Height',
			'tt_content.flexform_pi1.s_flash.loop' => 'Loop',
			'tt_content.flexform_pi1.s_flash.menu' => 'Menu',
			'tt_content.flexform_pi1.s_flash.quality' => 'Quality',
			'tt_content.flexform_pi1.s_flash.scale' => 'Scale',
			'tt_content.flexform_pi1.s_flash.salign' => 'Align',
			'tt_content.flexform_pi1.s_flash.bgcolor' => 'BGColor',
			'tt_content.flexform_pi1.s_flash.bgcolor.wizard' => 'Color picker',
			'tt_content.flexform_pi1.s_flash.swliveconnect' => 'SWLiveConnect',
			'tt_content.flexform_pi1.LGL.default' => 'Default',
			'tt_content.flexform_pi1.LGL.no' => 'No',
			'tt_content.flexform_pi1.LGL.yes' => 'Yes',
		),
		'fr' => Array (
			'tt_content.list_type_pi1' => 'Weleda Sport',
			'tx_weledasport_cat' => 'Weleda - Catégorie',
			'tx_weledasport_cat.name' => 'Nom',
			'tx_weledasport_cat.season' => 'Saison',
			'tx_weledasport_cat.season.I.0' => 'Hiver',
			'tx_weledasport_cat.season.I.1' => 'Eté',
			'tx_weledasport_sportsmen' => 'Weleda - Sportif',
			'tx_weledasport_sportsmen.name' => 'Nom',
			'tx_weledasport_sportsmen.car' => 'Catégorie',
			'tx_weledasport_sportsmen.link' => 'Site internet',
			'tx_weledasport_sportsmen.description' => 'Description',
			'tx_weledasport_sportsmen.palmares' => 'Palmarès',
			'tx_weledasport_sportsmen.palmares.section' => 'Ajouter un nouveau palmarès',
			'tx_weledasport_sportsmen.palmares.text' => 'Texte',
			'tx_weledasport_sportsmen.advice' => 'Conseil',
			'tx_weledasport_sportsmen.product' => 'Conseil d\'utilisation',
			'tx_weledasport_sportsmen.picture' => 'Image',
			'tx_weledasport_sportsmen.thumbnail' => 'Miniature',
			'tt_content.flexform_pi1.s_def' => 'Général',
			'tt_content.flexform_pi1.s_flash' => 'Paramètres Flash',
			'tt_content.flexform_pi1.s_flash.version' => 'Version',
			'tt_content.flexform_pi1.s_flash.width' => 'Largeur',
			'tt_content.flexform_pi1.s_flash.height' => 'Hauteur',
			'tt_content.flexform_pi1.s_flash.loop' => 'Boucle',
			'tt_content.flexform_pi1.s_flash.menu' => 'Menu',
			'tt_content.flexform_pi1.s_flash.quality' => 'Qualité',
			'tt_content.flexform_pi1.s_flash.scale' => 'Redimensionnement',
			'tt_content.flexform_pi1.s_flash.salign' => 'Alignement',
			'tt_content.flexform_pi1.s_flash.bgcolor' => 'Couleur de fond',
			'tt_content.flexform_pi1.s_flash.bgcolor.wizard' => 'Sélecteur de couleurs',
			'tt_content.flexform_pi1.s_flash.swliveconnect' => 'SWLiveConnect',
			'tt_content.flexform_pi1.LGL.default' => 'Par défaut',
			'tt_content.flexform_pi1.LGL.no' => 'Non',
			'tt_content.flexform_pi1.LGL.yes' => 'Oui',
		),
	);
?>
