<?php
	/**
	 * Language labels for database tables/fields belonging to extension 'wessex'
	 * 
	 * This file is detected by the translation tool.
	 */
	$LOCAL_LANG = Array (
		'default' => Array (
			'tx_wessex_languages' => 'Wessex - Language',
			'tx_wessex_languages.name' => 'Name',
			'tx_wessex_languages.color' => 'Color',
			'tx_wessex_countries' => 'Wessex - Country',
			'tx_wessex_countries.s_main' => 'Main',
			'tx_wessex_countries.s_infos' => 'Infos',
			'tx_wessex_countries.name' => 'Name',
			'tx_wessex_countries.id_language' => 'Language',
			'tx_wessex_countries.informations' => 'General informations',
			'tx_wessex_cities' => 'Wessex - City',
			'tx_wessex_cities.s_main' => 'Main',
			'tx_wessex_cities.s_infos' => 'Infos',
			'tx_wessex_cities.s_files' => 'Files',
			'tx_wessex_cities.name' => 'Name',
			'tx_wessex_cities.id_country' => 'Country',
			'tx_wessex_cities.id_coursetypes' => 'Course types',
			'tx_wessex_cities.description' => 'Description',
			'tx_wessex_cities.informations' => 'Informations',
			'tx_wessex_cities.infobox_1' => 'Info box 1',
			'tx_wessex_cities.infobox_2' => 'Info box 2',
			'tx_wessex_cities.front_picture' => 'Big picture',
			'tx_wessex_cities.credit' => 'Credit',
			'tx_wessex_cities.credit_url' => 'Credit link',
			'tx_wessex_cities.map' => 'Map',
			'tx_wessex_cities.pictures' => 'Pictures',
			'tx_wessex_cities.info_tables' => 'Tables',
			'tx_wessex_coursetypes' => 'Wessex - Course type',
			'tx_wessex_coursetypes.name' => 'Name',
			'tx_wessex_coursetypes.id_categories' => 'Category',
			'tx_wessex_coursecategories' => 'Wessex - Course category',
			'tx_wessex_coursecategories.name' => 'Name',
			'tt_content.list_type_pi1' => 'Wessex - Linguistic stays',
			'tt_content.list_type_pi2' => 'Wessex - Courses index',
			'tx_wessex_pi1.pi_flexform.front_picture_maxw' => 'Big picture max width',
			'tx_wessex_pi1.pi_flexform.front_picture_maxh' => 'Big picture max height',
			'tx_wessex_pi1.pi_flexform.map_maxw' => 'Map max width',
			'tx_wessex_pi1.pi_flexform.map_maxh' => 'Map max height',
			'tx_wessex_pi1.pi_flexform.pictures_maxw' => 'Pictures max width',
			'tx_wessex_pi1.pi_flexform.pictures_maxh' => 'Pictures max height',
		),
		'fr' => Array (
			'tx_wessex_languages' => 'Wessex - Langage',
			'tx_wessex_languages.name' => 'Nom',
			'tx_wessex_languages.color' => 'Couleur',
			'tx_wessex_countries' => 'Wessex - Pays',
			'tx_wessex_countries.s_main' => 'Général',
			'tx_wessex_countries.s_infos' => 'Infos',
			'tx_wessex_countries.name' => 'Nom',
			'tx_wessex_countries.id_language' => 'Langage',
			'tx_wessex_countries.informations' => 'Informations générales',
			'tx_wessex_cities' => 'Wessex - Ville',
			'tx_wessex_cities.s_main' => 'Général',
			'tx_wessex_cities.s_infos' => 'Infos',
			'tx_wessex_cities.s_files' => 'Fichiers',
			'tx_wessex_cities.name' => 'Nom',
			'tx_wessex_cities.id_country' => 'Pays',
			'tx_wessex_cities.id_coursetypes' => 'Types de cours',
			'tx_wessex_cities.description' => 'Description',
			'tx_wessex_cities.informations' => 'Informations',
			'tx_wessex_cities.infobox_1' => 'Boîte d\'infos 1',
			'tx_wessex_cities.infobox_2' => 'Boîte d\'infos 2',
			'tx_wessex_cities.front_picture' => 'Grande image',
			'tx_wessex_cities.credit' => 'Crédit',
			'tx_wessex_cities.credit_url' => 'Lien du crédit',
			'tx_wessex_cities.map' => 'Cartes',
			'tx_wessex_cities.pictures' => 'Images',
			'tx_wessex_cities.info_tables' => 'Tables',
			'tx_wessex_coursetypes' => 'Wessex - Type de cours',
			'tx_wessex_coursetypes.name' => 'Nom',
			'tx_wessex_coursetypes.id_categories' => 'Catégorie',
			'tx_wessex_coursecategories' => 'Wessex - Catégorie de cours',
			'tx_wessex_coursecategories.name' => 'Nom',
			'tt_content.list_type_pi1' => 'Wessex - Séjour linguistique',
			'tt_content.list_type_pi2' => 'Wessex - Index des cours',
			'tx_wessex_pi1.pi_flexform.front_picture_maxw' => 'Largeur max de la grande image',
			'tx_wessex_pi1.pi_flexform.front_picture_maxh' => 'Hauteur max de la grande image',
			'tx_wessex_pi1.pi_flexform.map_maxw' => 'Largeur max de la carte',
			'tx_wessex_pi1.pi_flexform.map_maxh' => 'Hauteur max de la carte',
			'tx_wessex_pi1.pi_flexform.pictures_maxw' => 'Largeur max des images',
			'tx_wessex_pi1.pi_flexform.pictures_maxh' => 'Hauteur max des images',
		),
	);
?>
