<?php
	/**
	 * Language labels for database tables/fields belonging to extension "eesp_basedocs"
	 *
	 * This file is detected by the translation tool.
	 */
	$LOCAL_LANG = Array (
		'default' => Array (
			'tt_content.list_type_pi1' => 'EESP - Base Documents',
			'tx_eespbasedocs_pi1.pi_flexform.s_def' => 'General settings',
			'tx_eespbasedocs_pi1.pi_flexform.s_category' => 'Category settings',
			'tx_eespbasedocs_pi1.pi_flexform.s_category.expand_levels' => 'Number of levels to expand',
			'tx_eespbasedocs_categories' => 'EESP - Category',
			'tx_eespbasedocs_categories.name' => 'Name',
			'tx_eespbasedocs_instances' => 'EESP - Instance',
			'tx_eespbasedocs_instances.title' => 'Title',
			'tx_eespbasedocs_instances.operation' => 'Operation',
			'tx_eespbasedocs_instances.members' => 'Members',
			'tx_eespbasedocs_instances.members.section' => 'Add a member',
			'tx_eespbasedocs_instances.members.name' => 'Name',
			'tx_eespbasedocs_instances.members.comment' => 'Comment',
			'tx_eespbasedocs_instances.members.function' => 'Function',
			'tx_eespbasedocs_instances.responsabilities' => 'Responsabilities',
			'tx_eespbasedocs_instances.goals' => 'Goals',
			'tx_eespbasedocs_instances.communications' => 'Communications',
			'tx_eespbasedocs_instances.communications.section' => 'Add a document',
			'tx_eespbasedocs_instances.communications.document' => 'Document',
			'tx_eespbasedocs_instances.communications.to' => 'To',
			'tx_eespbasedocs_instances.communications.from' => 'From',
			'tx_eespbasedocs_instances.communications.disposition' => 'Disposition',
			'tx_eespbasedocs_instances.activities' => 'Activities',
			'tx_eespbasedocs_instances.activities.section' => 'Add an activity',
			'tx_eespbasedocs_instances.activities.activity' => 'Activity',
			'tx_eespbasedocs_instances.activities.incharge' => 'Person in charge',
			'tx_eespbasedocs_instances.activities.duedate' => 'Due date',
			'tx_eespbasedocs_instances.activities.pointing' => 'Pointing',
			'tx_eespbasedocs_activity' => 'EESP - Activity / Mission',
			'tx_eespbasedocs_activity.title' => 'Title',
			'tx_eespbasedocs_activity.cat' => 'Category',
			'tx_eespbasedocs_activity.description' => 'Description',
			'tx_eespbasedocs_activity.incharge' => 'Person(s) in charge',
			'tx_eespbasedocs_activity.incharge.section' => 'Add a person in charge',
			'tx_eespbasedocs_activity.incharge.name' => 'Name',
			'tx_eespbasedocs_activity.incharge.function' => 'Function',
			'tx_eespbasedocs_activity.secretariat' => 'Secretariat',
			'tx_eespbasedocs_activity.secretariat.section' => 'Add a secretariat',
			'tx_eespbasedocs_activity.secretariat.name' => 'Name',
			'tx_eespbasedocs_activity.secretariat.function' => 'Function',
			'tx_eespbasedocs_activity.reference' => 'References',
			'tx_eespbasedocs_activity.public' => 'Target public / Application field',
			'tx_eespbasedocs_activity.goals' => 'Goals',
			'tx_eespbasedocs_activity.domains' => 'Domains',
			'tx_eespbasedocs_activity.collab_internal' => 'Internal collaborations',
			'tx_eespbasedocs_activity.collab_external' => 'External collaborations',
			'tx_eespbasedocs_activity.documents' => 'Documents and internet links',
			'tx_eespbasedocs_activity.documents.section' => 'Add a new document',
			'tx_eespbasedocs_activity.documents.name' => 'Name',
			'tx_eespbasedocs_activity.documents.label' => 'Label',
			'tx_eespbasedocs_activity.documents.url' => 'URL',
			'tx_eespbasedocs_activity.instances' => 'Instances',
		),
		'fr' => Array (
			'tt_content.list_type_pi1' => 'EESP - Documents de base',
			'tx_eespbasedocs_pi1.pi_flexform.s_def' => 'Paramètres de base',
			'tx_eespbasedocs_pi1.pi_flexform.s_category' => 'Paramètres des catégories',
			'tx_eespbasedocs_pi1.pi_flexform.s_category.expand_levels' => 'Nombre de niveau à afficher',
			'tx_eespbasedocs_categories' => 'EESP - Catégorie',
			'tx_eespbasedocs_categories.name' => 'Nom',
			'tx_eespbasedocs_instances' => 'EESP - Instance',
			'tx_eespbasedocs_instances.title' => 'Titre',
			'tx_eespbasedocs_instances.operation' => 'Fonctionnement',
			'tx_eespbasedocs_instances.members' => 'Membres',
			'tx_eespbasedocs_instances.members.section' => 'Ajouter un membre',
			'tx_eespbasedocs_instances.members.name' => 'Nom',
			'tx_eespbasedocs_instances.members.comment' => 'Commentaire',
			'tx_eespbasedocs_instances.members.function' => 'Fonction',
			'tx_eespbasedocs_instances.responsabilities' => 'Prérogatives et responsabilités',
			'tx_eespbasedocs_instances.goals' => 'Objectifs et tâches principales',
			'tx_eespbasedocs_instances.communications' => 'Liste de communication',
			'tx_eespbasedocs_instances.communications.section' => 'Ajouter une communication',
			'tx_eespbasedocs_instances.communications.document' => 'Document',
			'tx_eespbasedocs_instances.communications.to' => 'Adressé à',
			'tx_eespbasedocs_instances.communications.from' => 'Par',
			'tx_eespbasedocs_instances.communications.disposition' => 'Document à disposition',
			'tx_eespbasedocs_instances.activities' => 'Liste d\'activités',
			'tx_eespbasedocs_instances.activities.section' => 'Ajouter une activité',
			'tx_eespbasedocs_instances.activities.activity' => 'Activités / Etapes importantes',
			'tx_eespbasedocs_instances.activities.incharge' => 'Responsable',
			'tx_eespbasedocs_instances.activities.duedate' => 'Echéance',
			'tx_eespbasedocs_instances.activities.pointing' => 'Pointage intermédiaire',
			'tx_eespbasedocs_activity' => 'EESP - Activité / Mission',
			'tx_eespbasedocs_activity.title' => 'Titre',
			'tx_eespbasedocs_activity.cat' => 'Catégorie',
			'tx_eespbasedocs_activity.description' => 'Description',
			'tx_eespbasedocs_activity.incharge' => 'Responsable(s)',
			'tx_eespbasedocs_activity.incharge.section' => 'Add un responsable',
			'tx_eespbasedocs_activity.incharge.name' => 'Nom',
			'tx_eespbasedocs_activity.incharge.function' => 'Fonction',
			'tx_eespbasedocs_activity.secretariat' => 'Secrétariat',
			'tx_eespbasedocs_activity.secretariat.section' => 'Ajouter un secretariat',
			'tx_eespbasedocs_activity.secretariat.name' => 'Nom',
			'tx_eespbasedocs_activity.secretariat.function' => 'Fonction',
			'tx_eespbasedocs_activity.reference' => 'Références formelles',
			'tx_eespbasedocs_activity.public' => 'Public cible / Champ d\'application',
			'tx_eespbasedocs_activity.goals' => 'Finalités / Buts',
			'tx_eespbasedocs_activity.domains' => 'Domaines de compétence',
			'tx_eespbasedocs_activity.collab_internal' => 'Collaborations internes',
			'tx_eespbasedocs_activity.collab_external' => 'Collaborations externes',
			'tx_eespbasedocs_activity.documents' => 'Documents et liens internet',
			'tx_eespbasedocs_activity.documents.section' => 'Ajouter un nouveau document',
			'tx_eespbasedocs_activity.documents.name' => 'Nom',

			'tx_eespbasedocs_activity.documents.label' => 'Label',
			'tx_eespbasedocs_activity.documents.url' => 'URL',
			'tx_eespbasedocs_activity.instances' => 'Instances',
		),
	);
?>
