TYPO3-OOP: tx_oop_Flexform_Field_Input_Exception Class Reference
tx_oop_Flexform_Field_Input_Exception Class Reference
Public Member Functions
__toString ()
Returns the exception message with the backtrace if required.
getInfos ()
Gets the informations about the exception.
Static Public Member Functions
static setDebugState ($value)
Decide wether to display the backtrace or not when an exception is not caught.
Data Fields
const EXCEPTION_INVALID_EVAL = 0x01
Error codes for the exceptions.
Protected Member Functions
_getArgs (array $args)
Creates informations about arguments (type, value, etc).
_getCode ($file, $line)
Gets some PHP code line from a file.
_traceHistory ()
Gets the trace history.
_traceInfo ($label, $value)
Create an information section about a trace information.
_traceTitle ($title)
Creates an H1 title.
Static Protected Attributes
static $_commonStyles = 'font-family: Verdana, sans-serif; font-size: 10px; color: #898989;'
The common CSS styles for the HTML elements produced by this class.
static $_debug = true
Wheter to print the backtrace or not, when an exception is not caught.
Detailed Description
Definition at line 38 of file Exception.class.php.
Member Function Documentation
tx_oop_Core_Exception_Base::__toString () [inherited]
Returns the exception message with the backtrace if required.
Returns:
string The exception message prepended with the backtrace if required
See also:
getInfos
Definition at line 71 of file Base.class.php.
References tx_oop_Core_Exception_Base::getInfos().
tx_oop_Core_Exception_Base::_getArgs (array $ args) [protected, inherited]
Creates informations about arguments (type, value, etc).
Parameters:
array The arguments
Returns:
string The formatted informations about the arguments
Definition at line 169 of file Base.class.php.
Referenced by tx_oop_Core_Exception_Base::_traceHistory().
tx_oop_Core_Exception_Base::_getCode ($ file, $ line) [protected, inherited]
Gets some PHP code line from a file.
This method will return the requested line from the requested PHP file, as well as 4 line before and 4 lines after, if available.
Parameters:
string The path to the PHP file
int The line to get
Returns:
string The formatted PHP lines
Definition at line 242 of file Base.class.php.
Referenced by tx_oop_Core_Exception_Base::_traceHistory().
tx_oop_Core_Exception_Base::_traceHistory () [protected, inherited]
Gets the trace history.
Returns:
string The formatted full backtrace
See also:
_traceInfo
_getArgs
_getCode
Definition at line 123 of file Base.class.php.
References tx_oop_Core_Exception_Base::_getArgs(), tx_oop_Core_Exception_Base::_getCode(), and tx_oop_Core_Exception_Base::_traceInfo().
Referenced by tx_oop_Core_Exception_Base::getInfos().
tx_oop_Core_Exception_Base::_traceInfo ($ label, $ value) [protected, inherited]
Create an information section about a trace information.
Parameters:
string The label to display
string The text to display
Returns:
string The information section
Definition at line 103 of file Base.class.php.
Referenced by tx_oop_Core_Exception_Base::_traceHistory(), and tx_oop_Core_Exception_Base::getInfos().
tx_oop_Core_Exception_Base::_traceTitle ($ title) [protected, inherited]
Creates an H1 title.
Parameters:
string The title text
Returns:
string The H1 tag
Definition at line 90 of file Base.class.php.
Referenced by tx_oop_Core_Exception_Base::getInfos().
tx_oop_Core_Exception_Base::getInfos () [inherited]
Gets the informations about the exception.
Returns:
string The formatted informations bout the exception
See also:
_traceTitle
_traceInfo
_traceHistory
Definition at line 299 of file Base.class.php.
References tx_oop_Core_Exception_Base::_traceHistory(), tx_oop_Core_Exception_Base::_traceInfo(), and tx_oop_Core_Exception_Base::_traceTitle().
Referenced by tx_oop_Core_Exception_Base::__toString().
static tx_oop_Core_Exception_Base::setDebugState ($ value) [static, inherited]
Decide wether to display the backtrace or not when an exception is not caught.
Parameters:
boolean True if the backtrace must be displayed, otherwise false
Returns:
boolean The previous value
Definition at line 279 of file Base.class.php.
Field Documentation
tx_oop_Core_Exception_Base::$_commonStyles = 'font-family: Verdana, sans-serif; font-size: 10px; color: #898989;' [static, protected, inherited]
The common CSS styles for the HTML elements produced by this class.
Definition at line 48 of file Base.class.php.
tx_oop_Core_Exception_Base::$_debug = true [static, protected, inherited]
Wheter to print the backtrace or not, when an exception is not caught.
Definition at line 43 of file Base.class.php.
const tx_oop_Flexform_Field_Input_Exception::EXCEPTION_INVALID_EVAL = 0x01
Error codes for the exceptions.
Definition at line 43 of file Exception.class.php.
The documentation for this class was generated from the following file:
tx/oop/Flexform/Field/Input/Exception.class.php