TYPO3-OOP: tx_oop_Session_Data_Base Class Reference
tx_oop_Session_Data_Base Class Reference
Public Member Functions
__get ($name)
__isset ($name)
__set ($name, $value)
__toString ()
__unset ($name)
current ()
key ()
next ()
offsetExists ($name)
offsetGet ($name)
offsetSet ($name, $value)
offsetUnset ($name)
rewind ()
valid ()
Static Public Member Functions
static getInstance ($name)
Protected Member Functions
_getSessionData ()
_getUser ()
_updateSessionData ()
Static Protected Member Functions
static _getInstance ($class, $name)
Protected Attributes
$_data = array()
$_instanceName = ''
$_user = NULL
Private Member Functions
__construct ($name)
Private Attributes
$_iteratorIndex = 0
Static Private Attributes
static $_instances = array()
static $_nbInstances = 0
Detailed Description
Definition at line 38 of file Base.class.php.
Constructor & Destructor Documentation
tx_oop_Session_Data_Base::__construct ($ name) [private]
Definition at line 93 of file Base.class.php.
References _getSessionData(), and _getUser().
Member Function Documentation
tx_oop_Session_Data_Base::__get ($ name)
Definition at line 116 of file Base.class.php.
tx_oop_Session_Data_Base::__isset ($ name)
Definition at line 133 of file Base.class.php.
tx_oop_Session_Data_Base::__set ($ name, $ value)
Definition at line 124 of file Base.class.php.
References _updateSessionData().
tx_oop_Session_Data_Base::__toString ()
Definition at line 108 of file Base.class.php.
tx_oop_Session_Data_Base::__unset ($ name)
Definition at line 141 of file Base.class.php.
References _updateSessionData().
static tx_oop_Session_Data_Base::_getInstance ($ class, $ name) [static, protected]
Definition at line 225 of file Base.class.php.
Referenced by tx_oop_Session_Data_Frontend::getInstance(), and tx_oop_Session_Data_Backend::getInstance().
tx_oop_Session_Data_Base::_getSessionData () [abstract, protected]
Reimplemented in tx_oop_Session_Data_Backend, and tx_oop_Session_Data_Frontend.
Referenced by __construct().
tx_oop_Session_Data_Base::_getUser () [abstract, protected]
Reimplemented in tx_oop_Session_Data_Backend, and tx_oop_Session_Data_Frontend.
Referenced by __construct().
tx_oop_Session_Data_Base::_updateSessionData () [abstract, protected]
Reimplemented in tx_oop_Session_Data_Backend, and tx_oop_Session_Data_Frontend.
Referenced by __set(), __unset(), offsetSet(), and offsetUnset().
tx_oop_Session_Data_Base::current ()
Definition at line 192 of file Base.class.php.
static tx_oop_Session_Data_Base::getInstance ($ name) [static, abstract]
Reimplemented in tx_oop_Session_Data_Backend, and tx_oop_Session_Data_Frontend.
tx_oop_Session_Data_Base::key ()
Definition at line 184 of file Base.class.php.
tx_oop_Session_Data_Base::next ()
Definition at line 200 of file Base.class.php.
tx_oop_Session_Data_Base::offsetExists ($ name)
Definition at line 167 of file Base.class.php.
tx_oop_Session_Data_Base::offsetGet ($ name)
Definition at line 150 of file Base.class.php.
tx_oop_Session_Data_Base::offsetSet ($ name, $ value)
Definition at line 158 of file Base.class.php.
References _updateSessionData().
tx_oop_Session_Data_Base::offsetUnset ($ name)
Definition at line 175 of file Base.class.php.
References _updateSessionData().
tx_oop_Session_Data_Base::rewind ()
Definition at line 217 of file Base.class.php.
tx_oop_Session_Data_Base::valid ()
Definition at line 209 of file Base.class.php.
Field Documentation
tx_oop_Session_Data_Base::$_data = array() [protected]
Definition at line 88 of file Base.class.php.
tx_oop_Session_Data_Base::$_instanceName = '' [protected]
Definition at line 83 of file Base.class.php.
tx_oop_Session_Data_Base::$_instances = array() [static, private]
Definition at line 63 of file Base.class.php.
tx_oop_Session_Data_Base::$_iteratorIndex = 0 [private]
Definition at line 73 of file Base.class.php.
tx_oop_Session_Data_Base::$_nbInstances = 0 [static, private]
Definition at line 68 of file Base.class.php.
tx_oop_Session_Data_Base::$_user = NULL [protected]
Definition at line 78 of file Base.class.php.
The documentation for this class was generated from the following file:
tx/oop/Session/Data/Base.class.php