TYPO3-OOP: tx_oop_Xhtml_Tag Class Reference
tx_oop_Xhtml_Tag Class Reference
Detailed Description
Definition at line 38 of file Tag.class.php.
Public Member Functions
__call ($name, array $args=array())
__construct ($tagName)
__get ($name)
__set ($name, $value)
__toString ()
addChildNode (tx_oop_Xhtml_Tag $child)
addTextData ($data)
asHtml ()
asXml ()
current ()
Returns the current tag (SPL Iterator method).
getParent ($parentIndex=0)
key ()
Gets the tag name for the current tag (SPL Iterator method).
next ()
Moves the position to the next tag (SPL Iterator method).
offsetExists ($offset)
offsetGet ($offset)
offsetSet ($offset, $value)
offsetUnset ($offset)
rewind ()
Moves the position to the first tag (SPL Iterator method).
valid ()
Checks for a current tag (SPL Iterator method).
Static Public Member Functions
static useFormattedOutput ($value)
Protected Member Functions
_addChild ($name)
_addComment ($text)
_addSpacer ($pixels)
_output ($xmlCompliant=false, $level=0)
Returns the output of the current tag.
Protected Attributes
$_attribs = array()
The attributes of the current tag.
$_children = array()
$_childrenByName = array()
$_childrenCount = 0
$_childrenCountByName = array()
$_hasNodeChildren = false
$_iteratorIndex = 0
The current position for the SPL Iterator methods.
$_parents = array()
$_tagName = ''
The name of the current tag.
Static Protected Attributes
static $_emptyTags
The list of the XHTML empty tags (as in the XHTML 1.0 Strict DTD).
static $_formattedOutput = true
Wether the output is formatted or not.
static $_hasStatic = false
Wether the static variables are set or not.
static $_NL = ''
The new line character.
static $_TAB = ''
The tabulation character.
Static Private Member Functions
static _setStaticVars ()
Sets the needed static variables.
Constructor & Destructor Documentation
tx_oop_Xhtml_Tag::__construct ($ tagName)
Reimplemented in tx_oop_Xhtml_Comment.
Definition at line 124 of file Tag.class.php.
Member Function Documentation
tx_oop_Xhtml_Tag::__call ($ name, array $ args = array())
Definition at line 164 of file Tag.class.php.
References _addComment(), and _addSpacer().
tx_oop_Xhtml_Tag::__get ($ name)
Definition at line 156 of file Tag.class.php.
References _addChild().
tx_oop_Xhtml_Tag::__set ($ name, $ value)
Definition at line 148 of file Tag.class.php.
References _addChild().
tx_oop_Xhtml_Tag::__toString ()
Definition at line 140 of file Tag.class.php.
References asHtml().
tx_oop_Xhtml_Tag::_addChild ($ name) [protected]
Definition at line 329 of file Tag.class.php.
Referenced by __get(), __set(), and _addSpacer().
tx_oop_Xhtml_Tag::_addComment ($ text) [protected]
Definition at line 304 of file Tag.class.php.
Referenced by __call().
tx_oop_Xhtml_Tag::_addSpacer ($ pixels) [protected]
Definition at line 293 of file Tag.class.php.
References _addChild().
Referenced by __call().
tx_oop_Xhtml_Tag::_output ($ xmlCompliant = false, $ level = 0) [protected]
Returns the output of the current tag.
Parameters:
boolean Wheter the output must be XML compliant
int The indentation level
Returns:
string The output of the current tag (tag name and content)
Reimplemented in tx_oop_Xhtml_Comment.
Definition at line 358 of file Tag.class.php.
Referenced by asHtml(), and asXml().
static tx_oop_Xhtml_Tag::_setStaticVars () [static, private]
Sets the needed static variables.
Returns:
NULL
Definition at line 267 of file Tag.class.php.
tx_oop_Xhtml_Tag::addChildNode (tx_oop_Xhtml_Tag $ child)
Definition at line 439 of file Tag.class.php.
Referenced by addTextData().
tx_oop_Xhtml_Tag::addTextData ($ data)
Definition at line 468 of file Tag.class.php.
References addChildNode().
tx_oop_Xhtml_Tag::asHtml ()
Definition at line 487 of file Tag.class.php.
References _output().
Referenced by __toString().
tx_oop_Xhtml_Tag::asXml ()
Definition at line 495 of file Tag.class.php.
References _output().
tx_oop_Xhtml_Tag::current ()
Returns the current tag (SPL Iterator method).
Returns:
tx_oop_Xhtml_Tag The current HTML tag object
Definition at line 227 of file Tag.class.php.
tx_oop_Xhtml_Tag::getParent ($ parentIndex = 0)
Definition at line 503 of file Tag.class.php.
tx_oop_Xhtml_Tag::key ()
Gets the tag name for the current tag (SPL Iterator method).
Returns:
int The name of the current tag
Definition at line 237 of file Tag.class.php.
tx_oop_Xhtml_Tag::next ()
Moves the position to the next tag (SPL Iterator method).
Returns:
NULL
Definition at line 247 of file Tag.class.php.
tx_oop_Xhtml_Tag::offsetExists ($ offset)
Definition at line 183 of file Tag.class.php.
tx_oop_Xhtml_Tag::offsetGet ($ offset)
Definition at line 191 of file Tag.class.php.
tx_oop_Xhtml_Tag::offsetSet ($ offset, $ value)
Definition at line 199 of file Tag.class.php.
tx_oop_Xhtml_Tag::offsetUnset ($ offset)
Definition at line 207 of file Tag.class.php.
tx_oop_Xhtml_Tag::rewind ()
Moves the position to the first tag (SPL Iterator method).
Returns:
NULL
Definition at line 217 of file Tag.class.php.
static tx_oop_Xhtml_Tag::useFormattedOutput ($ value) [static]
Definition at line 282 of file Tag.class.php.
tx_oop_Xhtml_Tag::valid ()
Checks for a current tag (SPL Iterator method).
Returns:
boolean
Definition at line 257 of file Tag.class.php.
Field Documentation
tx_oop_Xhtml_Tag::$_attribs = array() [protected]
The attributes of the current tag.
Definition at line 84 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_children = array() [protected]
Definition at line 89 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_childrenByName = array() [protected]
Definition at line 94 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_childrenCount = 0 [protected]
Definition at line 104 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_childrenCountByName = array() [protected]
Definition at line 99 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_emptyTags [static, protected]
Initial value:
 array(
        'area'  => true,
        'base'  => true,
        'br'    => true,
        'col'   => true,
        'img'   => true,
        'input' => true,
        'hr'    => true,
        'link'  => true,
        'meta'  => true,
        'param' => true
    )
The list of the XHTML empty tags (as in the XHTML 1.0 Strict DTD).
Definition at line 53 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_formattedOutput = true [static, protected]
Wether the output is formatted or not.
Definition at line 43 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_hasNodeChildren = false [protected]
Definition at line 109 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_hasStatic = false [static, protected]
Wether the static variables are set or not.
Definition at line 48 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_iteratorIndex = 0 [protected]
The current position for the SPL Iterator methods.
Definition at line 119 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_NL = '' [static, protected]
The new line character.
Definition at line 69 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_parents = array() [protected]
Definition at line 114 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_TAB = '' [static, protected]
The tabulation character.
Definition at line 74 of file Tag.class.php.
tx_oop_Xhtml_Tag::$_tagName = '' [protected]
The name of the current tag.
Definition at line 79 of file Tag.class.php.
The documentation for this class was generated from the following file:
tx/oop/Xhtml/Tag.class.php