TYPO3-OOP: tx_oop_Number_Utils Class Reference
tx_oop_Number_Utils Class Reference
Static Public Member Functions
static inRange ($number, $min, $max, $int=false)
Ensures a number is in a specified range.
Private Member Functions
__construct ()
Class constructor.
Detailed Description
Definition at line 38 of file Utils.class.php.
Constructor & Destructor Documentation
tx_oop_Number_Utils::__construct () [private]
Class constructor.
The class constructor is private as all methods from this class are static.
Returns:
NULL
Definition at line 48 of file Utils.class.php.
Member Function Documentation
static tx_oop_Number_Utils::inRange ($ number, $ min, $ max, $ int = false) [static]
Ensures a number is in a specified range.
This method forces the specified number into the boundaries of a minimum and maximum number.
Parameters:
numbe The number to check
number The minimum value
number The maximum value
boolean Evaluates the number as an integer
Returns:
number A number in the specified range
Definition at line 63 of file Utils.class.php.
Referenced by tx_oop_Color_Utils::createHexColor(), tx_oop_Color_Converter::hslToRgb(), tx_oop_Color_Converter::hsvToRgb(), tx_oop_Color_Converter::rgbToHsl(), and tx_oop_Color_Converter::rgbToHsv().
The documentation for this class was generated from the following file:
tx/oop/Number/Utils.class.php