TYPO3-OOP: tx_oop_Color_Converter Class Reference
tx_oop_Color_Converter Class Reference
Static Public Member Functions
static hslToHsv ($H, $S, $L, $round=true)
Converts HSL color values into HSV.
static hslToRgb ($H, $S, $L, $round=true)
Converts HSL color values into RGB.
static hsvToHsl ($H, $S, $V, $round=true)
Converts HSV color values into HSL.
static hsvToRgb ($H, $S, $V, $round=true)
Converts HSV color values into RGB.
static rgbToHsl ($R, $G, $B, $round=true)
Converts RGB color values into HSL.
static rgbToHsv ($R, $G, $B, $round=true)
Converts RGB color values into HSV.
Private Member Functions
__construct ()
Class constructor.
Detailed Description
Definition at line 38 of file Converter.class.php.
Constructor & Destructor Documentation
tx_oop_Color_Converter::__construct () [private]
Class constructor.
The class constructor is private as all methods from this class are static.
Returns:
NULL
Definition at line 48 of file Converter.class.php.
Member Function Documentation
static tx_oop_Color_Converter::hslToHsv ($ H, $ S, $ L, $ round = true) [static]
Converts HSL color values into HSV.
This method takes HSL (Hue-Saturation-Luminance) color values and converts them into HSV (Hue-Saturation-Value) color values.
Parameters:
number The hue value (0-360)
number The saturation value (0-100)
number The luminance value (0-100)
boolean Round final values
Returns:
array An array with HSV color values
Definition at line 545 of file Converter.class.php.
References hslToRgb(), and rgbToHsv().
static tx_oop_Color_Converter::hslToRgb ($ H, $ S, $ L, $ round = true) [static]
Converts HSL color values into RGB.
This method takes HSL (Hue-Saturation-Luminance) color values and converts them into RGB (Red-Green-Blue) color values. This is the reverse method of rgbToHsl().
Parameters:
number The hue value (0-360)
number The saturation value (0-100)
number The luminance value (0-100)
boolean Round final values
Returns:
array An array with RGB color values
Definition at line 184 of file Converter.class.php.
References tx_oop_Number_Utils::inRange().
Referenced by tx_oop_Color_Utils::createHexColor(), and hslToHsv().
static tx_oop_Color_Converter::hsvToHsl ($ H, $ S, $ V, $ round = true) [static]
Converts HSV color values into HSL.
This method takes HSV (Hue-Saturation-Value) color values and converts them into HSL (Hue-Saturation-Luminance) color values. This is the reverse method of hsl2hsv().
Parameters:
number The hue value (0-360)
number The saturation value (0-100)
number The value value (0-100)
boolean Round final values
Returns:
array An array with HSL color values
Definition at line 572 of file Converter.class.php.
References hsvToRgb(), and rgbToHsl().
static tx_oop_Color_Converter::hsvToRgb ($ H, $ S, $ V, $ round = true) [static]
Converts HSV color values into RGB.
This method takes HSV (Hue-Saturation-Value) color values and converts them into RGB (Red-Green-Blue) color values. This is the reverse method of rgb2hsv().
Parameters:
number The hue value (0-360)
number The saturation value (0-100)
number The value value (0-100)
boolean Round final values
Returns:
array An array with RGB color values
Definition at line 430 of file Converter.class.php.
References tx_oop_Number_Utils::inRange().
Referenced by tx_oop_Color_Utils::createHexColor(), and hsvToHsl().
static tx_oop_Color_Converter::rgbToHsl ($ R, $ G, $ B, $ round = true) [static]
Converts RGB color values into HSL.
This method takes RGB (Red-Green-Blue) color values and converts them into HSL (Hue-Saturation-Luminance) color values. RGB values are from 0 to 255, and HSL values are returned in an array with associative keys. Note that the returned hue value is an angle (0-360), and the saturation and luminance are percentage (0-100).
Parameters:
number The red value (0-255)
number The green value (0-255)
number The blue value (0-255)
boolean Round final values
Returns:
array An array with HSL color values
Definition at line 66 of file Converter.class.php.
References tx_oop_Number_Utils::inRange().
Referenced by hsvToHsl(), and tx_oop_Color_Utils::modifyHexColor().
static tx_oop_Color_Converter::rgbToHsv ($ R, $ G, $ B, $ round = true) [static]
Converts RGB color values into HSV.
This method takes RGB (Red-Green-Blue) color values and converts them into HSV (Hue-Saturation-Value) color values. RGB values are from 0 to 255, and HSV values are returned in an array with associative keys. Note that the returned hue value is an angle (0-360), and the saturation and value are percentage (0-100).
Parameters:
number The red value (0-255)
number The green value (0-255)
number The blue value (0-255)
boolean Round final values
Returns:
array An array with HSV color values
Definition at line 321 of file Converter.class.php.
References tx_oop_Number_Utils::inRange().
Referenced by hslToHsv(), and tx_oop_Color_Utils::modifyHexColor().
The documentation for this class was generated from the following file:
tx/oop/Color/Converter.class.php