TYPO3-OOP: tx_oop_Database_Layer Class Reference
tx_oop_Database_Layer Class Reference
Public Member Functions
__call ($name, array $args=array())
PHP method calls overloading.
__clone ()
Clones an instance of the class.
__destruct ()
Class destructor.
deleteRecord ($table, $id, $deleteFromTable=false)
enableFields ($table)
getRecord ($table, $id, $enableFields=true)
getRecordsByFields ($table, array $fieldsValues, $orderBy= '', $enableFields=true)
getRelatedRecords ($id, $localTable, $foreignTable, $relationTable, $orderBy= '', $enableFields=true)
insertRecord ($table, array $values)
removeDeletedRecords ($table)
updateRecord ($table, $id, array $values)
Static Public Member Functions
static getInstance ()
Gets the unique class instance.
Private Member Functions
__construct ()
Class constructor.
Private Attributes
$_drivers = array()
The available PDO drivers.
$_dsn = ''
The distinguised server name for the TYPO3 database.
$_pdo = NULL
The PDO object for the TYPO3 database.
Static Private Attributes
static $_instance = NULL
The unique instance of the class (singleton).
Detailed Description
Definition at line 41 of file Layer.class.php.
Constructor & Destructor Documentation
tx_oop_Database_Layer::__construct () [private]
Class constructor.
The class constructor is private to avoid multiple instances of the class (singleton).
Returns:
NULL
Exceptions:
tx_oop_Database_Layer_Exception If the PDO class is not available
tx_oop_Database_Layer_Exception If the PDO object cannot be created
Definition at line 73 of file Layer.class.php.
References tx_oop_Database_Layer_Exception::EXCEPTION_DBAL_INVALID_CONF, tx_oop_Database_Layer_Exception::EXCEPTION_NO_CONNECTION, and tx_oop_Database_Layer_Exception::EXCEPTION_NO_PDO_DRIVER.
tx_oop_Database_Layer::__destruct ()
Class destructor.
This method will close the PDO connection to the TYPO3 database.
Returns:
NULL
Definition at line 182 of file Layer.class.php.
Member Function Documentation
tx_oop_Database_Layer::__call ($ name, array $ args = array())
PHP method calls overloading.
This method will reroute all the call on this object to the PDO object.
Parameters:
string The name of the called method
array The arguments for the called method
Returns:
mixed The result of the PDO method called
Exceptions:
tx_oop_Database_Layer_Exception If the called method does not exist
Definition at line 197 of file Layer.class.php.
tx_oop_Database_Layer::__clone ()
Clones an instance of the class.
A call to this method will produce an exception, as the class cannot be cloned (singleton).
Returns:
NULL
Exceptions:
tx_oop_Core_Singleton_Exception Always, as the class cannot be cloned (singleton)
Definition at line 257 of file Layer.class.php.
References tx_oop_Core_Singleton_Exception::EXCEPTION_CLONE.
tx_oop_Database_Layer::deleteRecord ($ table, $ id, $ deleteFromTable = false)
Definition at line 601 of file Layer.class.php.
References updateRecord().
tx_oop_Database_Layer::enableFields ($ table)
Definition at line 289 of file Layer.class.php.
Referenced by getRecord(), getRecordsByFields(), and getRelatedRecords().
static tx_oop_Database_Layer::getInstance () [static]
Gets the unique class instance.
This method is used to get the unique instance of the class (singleton). If no instance is available, it will create it.
Returns:
tx_oop_Database_Layer The unique instance of the class
Definition at line 273 of file Layer.class.php.
Referenced by tx_oop_Plugin_Base::_setStaticVars(), and tx_oop_Module_Base::_setStaticVars().
tx_oop_Database_Layer::getRecord ($ table, $ id, $ enableFields = true)
Definition at line 313 of file Layer.class.php.
References enableFields().
tx_oop_Database_Layer::getRecordsByFields ($ table, array $ fieldsValues, $ orderBy = '', $ enableFields = true)
Definition at line 344 of file Layer.class.php.
References enableFields().
tx_oop_Database_Layer::getRelatedRecords ($ id, $ localTable, $ foreignTable, $ relationTable, $ orderBy = '', $ enableFields = true)
Definition at line 412 of file Layer.class.php.
References enableFields().
tx_oop_Database_Layer::insertRecord ($ table, array $ values)
Definition at line 473 of file Layer.class.php.
tx_oop_Database_Layer::removeDeletedRecords ($ table)
Definition at line 644 of file Layer.class.php.
tx_oop_Database_Layer::updateRecord ($ table, $ id, array $ values)
Definition at line 549 of file Layer.class.php.
Referenced by deleteRecord().
Field Documentation
tx_oop_Database_Layer::$_drivers = array() [private]
The available PDO drivers.
Definition at line 56 of file Layer.class.php.
tx_oop_Database_Layer::$_dsn = '' [private]
The distinguised server name for the TYPO3 database.
Definition at line 61 of file Layer.class.php.
tx_oop_Database_Layer::$_instance = NULL [static, private]
The unique instance of the class (singleton).
Definition at line 46 of file Layer.class.php.
tx_oop_Database_Layer::$_pdo = NULL [private]
The PDO object for the TYPO3 database.
Definition at line 51 of file Layer.class.php.
The documentation for this class was generated from the following file:
tx/oop/Database/Layer.class.php