TYPO3-OOP: tx_oop_Color_Utils Class Reference
tx_oop_Color_Utils Class Reference
Public Member Functions
createHexColor ($v1, $v2, $v3, $uppercase=false)
Creates an hexadecimal color.
modifyHexColor ($color, $v1, $v2, $v3, $uppercase=false)
Modifies an hexadecimal color.
setColorMethod ($method)
Protected Attributes
$_colorMethod = 'RGB'
The color method to use (RGB, HSL or HSV).
Detailed Description
Definition at line 38 of file Utils.class.php.
Member Function Documentation
tx_oop_Color_Utils::createHexColor ($ v1, $ v2, $ v3, $ uppercase = false)
Creates an hexadecimal color.
This method is used to create an hexadecimal color representation from RGB (Red-Green-Blue), HSL (Hue-Saturation-Luminance) or HSV (Hue-Saturation-Value) values.
Parameters:
number The first value (red or hue, depending of the method)
number The second value (green or saturation, depending of the method)
number The third value (blue, luminosity or value, depending of the method)
boolean Return value in uppercase
Returns:
string The hexadecimal value of the color
Definition at line 89 of file Utils.class.php.
References tx_oop_Color_Converter::hslToRgb(), tx_oop_Color_Converter::hsvToRgb(), and tx_oop_Number_Utils::inRange().
Referenced by modifyHexColor().
tx_oop_Color_Utils::modifyHexColor ($ color, $ v1, $ v2, $ v3, $ uppercase = false)
Modifies an hexadecimal color.
This method is used to modify an hexadecimal color representation by adding RGB (Red-Green-Blue), HSL (Hue-Saturation-Luminance) or HSV (Hue-Saturation-Value) values.
Parameters:
string The original color (hexadecimal)
number The first value (red or hue, depending of the method)
number The second value (green or saturation, depending of the method)
number The third value (blue, luminosity or value, depending of the method)
boolean Return value in uppercase
Returns:
string The hexadecimal value of the modified color
Definition at line 147 of file Utils.class.php.
References createHexColor(), tx_oop_Color_Converter::rgbToHsl(), and tx_oop_Color_Converter::rgbToHsv().
tx_oop_Color_Utils::setColorMethod ($ method)
Definition at line 48 of file Utils.class.php.
Field Documentation
tx_oop_Color_Utils::$_colorMethod = 'RGB' [protected]
The color method to use (RGB, HSL or HSV).
Definition at line 43 of file Utils.class.php.
The documentation for this class was generated from the following file:
tx/oop/Color/Utils.class.php