TYPO3-OOP: tx_oop_Lang_Getter Class Reference
tx_oop_Lang_Getter Class Reference
Public Member Functions
__get ($name)
getLabel ($name)
Static Public Member Functions
static getInstance ($langFile)
Private Member Functions
__construct ($langFile)
Static Private Member Functions
static _setCurrentLanguage ()
Private Attributes
$_instanceName = ''
$_labels = array()
$_langFilePath = ''
Static Private Attributes
static $_currentLang = ''
static $_defaultInstanceName = 'EXT:oop/lang/lgl.xml'
The name of the default instance.
static $_instances = array()
static $_nbInstances = 0
Detailed Description
Definition at line 38 of file Getter.class.php.
Constructor & Destructor Documentation
tx_oop_Lang_Getter::__construct ($ langFile) [private]
Definition at line 78 of file Getter.class.php.
References tx_oop_Lang_Getter_Exception::EXCEPTION_BAD_XML, and tx_oop_Lang_Getter_Exception::EXCEPTION_NO_LANG_FILE.
Member Function Documentation
tx_oop_Lang_Getter::__get ($ name)
Definition at line 118 of file Getter.class.php.
References getLabel().
static tx_oop_Lang_Getter::_setCurrentLanguage () [static, private]
Definition at line 126 of file Getter.class.php.
Referenced by getInstance().
static tx_oop_Lang_Getter::getInstance ($ langFile) [static]
Definition at line 141 of file Getter.class.php.
References _setCurrentLanguage().
Referenced by tx_oop_Plugin_Wizard_Icon::__construct(), tx_oop_Plugin_Base::__construct(), and tx_oop_Module_Base::__construct().
tx_oop_Lang_Getter::getLabel ($ name)
Definition at line 166 of file Getter.class.php.
Referenced by __get().
Field Documentation
tx_oop_Lang_Getter::$_currentLang = '' [static, private]
Definition at line 58 of file Getter.class.php.
tx_oop_Lang_Getter::$_defaultInstanceName = 'EXT:oop/lang/lgl.xml' [static, private]
The name of the default instance.
Definition at line 53 of file Getter.class.php.
tx_oop_Lang_Getter::$_instanceName = '' [private]
Definition at line 68 of file Getter.class.php.
tx_oop_Lang_Getter::$_instances = array() [static, private]
Definition at line 43 of file Getter.class.php.
tx_oop_Lang_Getter::$_labels = array() [private]
Definition at line 63 of file Getter.class.php.
tx_oop_Lang_Getter::$_langFilePath = '' [private]
Definition at line 73 of file Getter.class.php.
tx_oop_Lang_Getter::$_nbInstances = 0 [static, private]
Definition at line 48 of file Getter.class.php.
The documentation for this class was generated from the following file:
tx/oop/Lang/Getter.class.php