TYPO3-OOP: tx_oop_Typo3_Core_Engine Class Reference
tx_oop_Typo3_Core_Engine Class Reference
Public Member Functions
__call ($name, array $args=array())
PHP method calls overloading.
__clone ()
Clones an instance of the class.
__get ($name)
__isset ($name)
__set ($name, $value)
__unset ($name)
clearAllCache ()
clearCache ($id)
clearPagesCache ()
clearTempCache ()
copy ($table, $id, $value)
delete ($table, $id)
localize ($table, $id, $value)
move ($table, $id, $value)
newRecord ($table, array $fields)
processCommand (array $cmd)
processData (array $data)
unDelete ($table, $id)
updateRecord ($table, $id, array $fields)
version ($table, $id, array $value)
Static Public Member Functions
static getInstance ()
Gets the unique class instance.
Private Member Functions
__construct ()
Class constructor.
Private Attributes
$_tce = NULL
The TCE object.
Static Private Attributes
static $_instance = NULL
The unique instance of the class (singleton).
Detailed Description
Definition at line 41 of file Engine.class.php.
Constructor & Destructor Documentation
tx_oop_Typo3_Core_Engine::__construct () [private]
Class constructor.
The class constructor is private to avoid multiple instances of the class (singleton).
Returns:
NULL
Definition at line 61 of file Engine.class.php.
Member Function Documentation
tx_oop_Typo3_Core_Engine::__call ($ name, array $ args = array())
PHP method calls overloading.
This method will reroute all the call on this object to the TCE object.
Parameters:
string The name of the called method
array The arguments for the called method
Returns:
mixed The result of the TCE method called
Exceptions:
tx_oop_Typo3_Core_Engine_Exception If the called method does not exist
Definition at line 88 of file Engine.class.php.
tx_oop_Typo3_Core_Engine::__clone ()
Clones an instance of the class.
A call to this method will produce an exception, as the class cannot be cloned (singleton).
Returns:
NULL
Exceptions:
tx_oop_Core_Singleton_Exception Always, as the class cannot be cloned (singleton)
Definition at line 204 of file Engine.class.php.
References tx_oop_Core_Singleton_Exception::EXCEPTION_CLONE.
tx_oop_Typo3_Core_Engine::__get ($ name)
Definition at line 166 of file Engine.class.php.
tx_oop_Typo3_Core_Engine::__isset ($ name)
Definition at line 182 of file Engine.class.php.
tx_oop_Typo3_Core_Engine::__set ($ name, $ value)
Definition at line 174 of file Engine.class.php.
tx_oop_Typo3_Core_Engine::__unset ($ name)
Definition at line 190 of file Engine.class.php.
tx_oop_Typo3_Core_Engine::clearAllCache ()
Definition at line 370 of file Engine.class.php.
tx_oop_Typo3_Core_Engine::clearCache ($ id)
Definition at line 362 of file Engine.class.php.
tx_oop_Typo3_Core_Engine::clearPagesCache ()
Definition at line 378 of file Engine.class.php.
tx_oop_Typo3_Core_Engine::clearTempCache ()
Definition at line 386 of file Engine.class.php.
tx_oop_Typo3_Core_Engine::copy ($ table, $ id, $ value)
Definition at line 236 of file Engine.class.php.
References processCommand().
tx_oop_Typo3_Core_Engine::delete ($ table, $ id)
Definition at line 268 of file Engine.class.php.
References processCommand().
static tx_oop_Typo3_Core_Engine::getInstance () [static]
Gets the unique class instance.
This method is used to get the unique instance of the class (singleton). If no instance is available, it will create it.
Returns:
tx_oop_Database_Layer The unique instance of the class
Definition at line 220 of file Engine.class.php.
Referenced by tx_oop_Module_Base::_setStaticVars().
tx_oop_Typo3_Core_Engine::localize ($ table, $ id, $ value)
Definition at line 300 of file Engine.class.php.
References processCommand().
tx_oop_Typo3_Core_Engine::move ($ table, $ id, $ value)
Definition at line 252 of file Engine.class.php.
References processCommand().
tx_oop_Typo3_Core_Engine::newRecord ($ table, array $ fields)
Definition at line 332 of file Engine.class.php.
References processData().
tx_oop_Typo3_Core_Engine::processCommand (array $ cmd)
Definition at line 403 of file Engine.class.php.
Referenced by copy(), delete(), localize(), move(), unDelete(), and version().
tx_oop_Typo3_Core_Engine::processData (array $ data)
Definition at line 394 of file Engine.class.php.
Referenced by newRecord(), and updateRecord().
tx_oop_Typo3_Core_Engine::unDelete ($ table, $ id)
Definition at line 284 of file Engine.class.php.
References processCommand().
tx_oop_Typo3_Core_Engine::updateRecord ($ table, $ id, array $ fields)
Definition at line 348 of file Engine.class.php.
References processData().
tx_oop_Typo3_Core_Engine::version ($ table, $ id, array $ value)
Definition at line 316 of file Engine.class.php.
References processCommand().
Field Documentation
tx_oop_Typo3_Core_Engine::$_instance = NULL [static, private]
The unique instance of the class (singleton).
Definition at line 46 of file Engine.class.php.
tx_oop_Typo3_Core_Engine::$_tce = NULL [private]
The TCE object.
Definition at line 51 of file Engine.class.php.
The documentation for this class was generated from the following file:
tx/oop/Typo3/Core/Engine.class.php