TYPO3-OOP: tx_oop_Plugin_Base Class Reference
tx_oop_Plugin_Base Class Reference
Public Member Functions
__construct ()
main ($content, $conf)
Data Fields
$conf = array()
$extKey = ''
The extension key (needed by tslib_piBase).
$piVars = array()
$prefixId = ''
The class name (needed by tslib_piBase).
$scriptRelPath = ''
The script path, relative to the extension(needed by tslib_piBase).
Protected Member Functions
_countrySelect ($name, $emptyOptionAtStart=true)
Creates a select menu with countries from the 'static_countries' table.
_createThumbnail ($file, $width=100, $height=100, $newWindow=false, $newWindowWidth=800)
Creates a thumbnail.
_cssClass ($name, tx_oop_Xhtml_Tag $tag=NULL)
_feLogin ($user)
Establish a frontend user session.
_getFrontendTemplate ($path)
_getPluginContent (tx_oop_Xhtml_Tag $content)
The method used to get the plugin content, which has to be declared in the child classes.
_includeJQuery ()
Includes the jQuery JS framework.
_includeJQueryPlugin ($plugin)
Includes a jQuery plugin.
_includeJQueryUi ()
Includes the jQuery UI JS framework.
_includeMootools ()
Includes the Mootools JS framework.
_includePrototype ()
Includes the Prototype JS framework.
_includeScriptaculous ()
Includes the Scriptaculous JS framework.
_includeWebtoolkitScript ($script)
Includes a Webtoolkit script.
_registerHook ($name, array $params=array())
Protected Attributes
$_lang = NULL
$_piData = NULL
$_time = 0
$_url = ''
Static Protected Attributes
static $_client = array()
A reference to the client informations array.
static $_db = NULL
The instance of the database object (tx_oop_Database_Layer).
static $_str = NULL
The instance of the string utilities class (tx_oop_String_Utils).
static $_t3Conf = array()
A reference to the TYPO3 configuration variables array.
static $_t3Db = NULL
A reference to the t3lib_DB object.
static $_t3Lang = NULL
static $_tca = array()
A reference to the TCA array.
static $_tcaDescr = array()
A reference to the TCA description array.
static $_tsfe = NULL
A reference to the TSFE (tslib_fe) object.
Private Member Functions
_addJs ($path)
Static Private Member Functions
static _setStaticVars ()
Private Attributes
$_content = NULL
$_cssPrefix = ''
$_extDir = ''
$_pluginNumber = 0
The plugin number.
$_reflection = NULL
A reflection object for the frontend plugin.
$_uploadDirectory = ''
Static Private Attributes
static $_hasJQuery = false
Whether the jQuery JS framework has been included.
static $_hasJQueryUi = false
Whether the jQuery UI framework has been included.
static $_hasMootools = false
Whether the Mootools JS framework has been included.
static $_hasPrototype = false
Whether the Prototype JS framework has been included.
static $_hasScriptaculous = false
Whether the Scriptaculous JS framework has been included.
static $_hasStatic = false
A flag to know wether the needed static variables are set.
static $_jQueryLoadedPlugins = array()
The jQuery plugins that have been included.
static $_jQueryPluginsDeps
The dependancies for the jQuery plugins.
static $_oopPath = ''
static $_oopRelativePath = ''
static $_oopSiteRelativePath = ''
static $_webtoolkitLoadedScripts = array()
The webtoolkit scripts that have been included.
Detailed Description
Definition at line 41 of file Base.class.php.
Constructor & Destructor Documentation
tx_oop_Plugin_Base::__construct ()
Definition at line 236 of file Base.class.php.
References _setStaticVars(), tx_oop_Lang_Getter::getInstance(), and tx_oop_Session_Data_Frontend::getInstance().
Member Function Documentation
tx_oop_Plugin_Base::_addJs ($ path) [private]
Definition at line 303 of file Base.class.php.
Referenced by _includeJQuery(), _includeJQueryPlugin(), _includeJQueryUi(), _includeMootools(), _includePrototype(), _includeScriptaculous(), and _includeWebtoolkitScript().
tx_oop_Plugin_Base::_countrySelect ($ name, $ emptyOptionAtStart = true) [protected]
Creates a select menu with countries from the 'static_countries' table.
Parameters:
string The name of the select
boolean Wheter to add an empty option at start
Returns:
tx_oop_Xhtml_Tag The select menu with the countries
Definition at line 351 of file Base.class.php.
tx_oop_Plugin_Base::_createThumbnail ($ file, $ width = 100, $ height = 100, $ newWindow = false, $ newWindowWidth = 800) [protected]
Creates a thumbnail.
Parameters:
string The file path (relative to the upload directory). May be a comma list of path
int The thumbnail maximum width
int The thumbnail maximum height
boolean Wheter to add a link to display the original image in a new window
int The maximum width of the new window, if the $newWindow is set
Returns:
string The thumbnail picture(s)
Definition at line 422 of file Base.class.php.
tx_oop_Plugin_Base::_cssClass ($ name, tx_oop_Xhtml_Tag $ tag = NULL) [protected]
Definition at line 332 of file Base.class.php.
tx_oop_Plugin_Base::_feLogin ($ user) [protected]
Establish a frontend user session.
Parameters:
array The FE user row from the database
Returns:
NULL
Definition at line 391 of file Base.class.php.
tx_oop_Plugin_Base::_getFrontendTemplate ($ path) [protected]
Definition at line 614 of file Base.class.php.
tx_oop_Plugin_Base::_getPluginContent (tx_oop_Xhtml_Tag $ content) [abstract, protected]
The method used to get the plugin content, which has to be declared in the child classes.
Referenced by main().
tx_oop_Plugin_Base::_includeJQuery () [protected]
Includes the jQuery JS framework.
Returns:
NULL
Definition at line 460 of file Base.class.php.
References _addJs().
tx_oop_Plugin_Base::_includeJQueryPlugin ($ plugin) [protected]
Includes a jQuery plugin.
Available plugins are:
accordion
dimensions
Parameters:
string The name of the plugin to include
Returns:
NULL
Definition at line 587 of file Base.class.php.
References _addJs().
tx_oop_Plugin_Base::_includeJQueryUi () [protected]
Includes the jQuery UI JS framework.
Returns:
NULL
Definition at line 478 of file Base.class.php.
References _addJs().
tx_oop_Plugin_Base::_includeMootools () [protected]
Includes the Mootools JS framework.
Returns:
NULL
Definition at line 496 of file Base.class.php.
References _addJs().
tx_oop_Plugin_Base::_includePrototype () [protected]
Includes the Prototype JS framework.
Returns:
NULL
Definition at line 514 of file Base.class.php.
References _addJs().
Referenced by _includeScriptaculous().
tx_oop_Plugin_Base::_includeScriptaculous () [protected]
Includes the Scriptaculous JS framework.
Returns:
NULL
See also:
_includePrototype
Definition at line 533 of file Base.class.php.
References _addJs(), and _includePrototype().
tx_oop_Plugin_Base::_includeWebtoolkitScript ($ script) [protected]
Includes a Webtoolkit script.
Available scripts are:
base64
crc32
md5
sha1
sha256
url
utf8
Parameters:
string The name of the script to include
Returns:
NULL
Definition at line 564 of file Base.class.php.
References _addJs().
tx_oop_Plugin_Base::_registerHook ($ name, array $ params = array()) [protected]
Definition at line 316 of file Base.class.php.
static tx_oop_Plugin_Base::_setStaticVars () [static, private]
Definition at line 283 of file Base.class.php.
References tx_oop_String_Utils::getInstance(), and tx_oop_Database_Layer::getInstance().
Referenced by __construct().
tx_oop_Plugin_Base::main ($ content, $ conf)
Definition at line 625 of file Base.class.php.
References $conf, and _getPluginContent().
Field Documentation
tx_oop_Plugin_Base::$_client = array() [static, protected]
A reference to the client informations array.
Definition at line 151 of file Base.class.php.
tx_oop_Plugin_Base::$_content = NULL [private]
Definition at line 176 of file Base.class.php.
tx_oop_Plugin_Base::$_cssPrefix = '' [private]
Definition at line 161 of file Base.class.php.
tx_oop_Plugin_Base::$_db = NULL [static, protected]
The instance of the database object (tx_oop_Database_Layer).
Definition at line 116 of file Base.class.php.
tx_oop_Plugin_Base::$_extDir = '' [private]
Definition at line 186 of file Base.class.php.
tx_oop_Plugin_Base::$_hasJQuery = false [static, private]
Whether the jQuery JS framework has been included.
Definition at line 72 of file Base.class.php.
tx_oop_Plugin_Base::$_hasJQueryUi = false [static, private]
Whether the jQuery UI framework has been included.
Definition at line 77 of file Base.class.php.
tx_oop_Plugin_Base::$_hasMootools = false [static, private]
Whether the Mootools JS framework has been included.
Definition at line 82 of file Base.class.php.
tx_oop_Plugin_Base::$_hasPrototype = false [static, private]
Whether the Prototype JS framework has been included.
Definition at line 87 of file Base.class.php.
tx_oop_Plugin_Base::$_hasScriptaculous = false [static, private]
Whether the Scriptaculous JS framework has been included.
Definition at line 92 of file Base.class.php.
tx_oop_Plugin_Base::$_hasStatic = false [static, private]
A flag to know wether the needed static variables are set.
Definition at line 52 of file Base.class.php.
tx_oop_Plugin_Base::$_jQueryLoadedPlugins = array() [static, private]
The jQuery plugins that have been included.
Definition at line 102 of file Base.class.php.
tx_oop_Plugin_Base::$_jQueryPluginsDeps [static, private]
Initial value:
 array(
        'accordion' => array(
            'dimensions'
        )
    )
The dependancies for the jQuery plugins.
Definition at line 107 of file Base.class.php.
tx_oop_Plugin_Base::$_lang = NULL [protected]
Definition at line 166 of file Base.class.php.
tx_oop_Plugin_Base::$_oopPath = '' [static, private]
Definition at line 57 of file Base.class.php.
tx_oop_Plugin_Base::$_oopRelativePath = '' [static, private]
Definition at line 62 of file Base.class.php.
tx_oop_Plugin_Base::$_oopSiteRelativePath = '' [static, private]
Definition at line 67 of file Base.class.php.
tx_oop_Plugin_Base::$_piData = NULL [protected]
Definition at line 206 of file Base.class.php.
tx_oop_Plugin_Base::$_pluginNumber = 0 [private]
The plugin number.
Definition at line 181 of file Base.class.php.
tx_oop_Plugin_Base::$_reflection = NULL [private]
A reflection object for the frontend plugin.
Definition at line 171 of file Base.class.php.
tx_oop_Plugin_Base::$_str = NULL [static, protected]
The instance of the string utilities class (tx_oop_String_Utils).
Definition at line 121 of file Base.class.php.
tx_oop_Plugin_Base::$_t3Conf = array() [static, protected]
A reference to the TYPO3 configuration variables array.
Definition at line 156 of file Base.class.php.
tx_oop_Plugin_Base::$_t3Db = NULL [static, protected]
A reference to the t3lib_DB object.
Definition at line 131 of file Base.class.php.
tx_oop_Plugin_Base::$_t3Lang = NULL [static, protected]
Definition at line 136 of file Base.class.php.
tx_oop_Plugin_Base::$_tca = array() [static, protected]
A reference to the TCA array.
Definition at line 146 of file Base.class.php.
tx_oop_Plugin_Base::$_tcaDescr = array() [static, protected]
A reference to the TCA description array.
Definition at line 141 of file Base.class.php.
tx_oop_Plugin_Base::$_time = 0 [protected]
Definition at line 196 of file Base.class.php.
tx_oop_Plugin_Base::$_tsfe = NULL [static, protected]
A reference to the TSFE (tslib_fe) object.
Definition at line 126 of file Base.class.php.
tx_oop_Plugin_Base::$_uploadDirectory = '' [private]
Definition at line 191 of file Base.class.php.
tx_oop_Plugin_Base::$_url = '' [protected]
Definition at line 201 of file Base.class.php.
tx_oop_Plugin_Base::$_webtoolkitLoadedScripts = array() [static, private]
The webtoolkit scripts that have been included.
Definition at line 97 of file Base.class.php.
tx_oop_Plugin_Base::$conf = array()
Definition at line 226 of file Base.class.php.
Referenced by main().
tx_oop_Plugin_Base::$extKey = ''
The extension key (needed by tslib_piBase).
Definition at line 221 of file Base.class.php.
tx_oop_Plugin_Base::$piVars = array()
Definition at line 231 of file Base.class.php.
tx_oop_Plugin_Base::$prefixId = ''
The class name (needed by tslib_piBase).
Definition at line 211 of file Base.class.php.
tx_oop_Plugin_Base::$scriptRelPath = ''
The script path, relative to the extension(needed by tslib_piBase).
Definition at line 216 of file Base.class.php.
The documentation for this class was generated from the following file:
tx/oop/Plugin/Base.class.php