TYPO3-OOP: tx_oop_Module_Base Class Reference
tx_oop_Module_Base Class Reference
Public Member Functions
__construct ()
__toString ()
createModulePage ()
menuConfig ()
Data Fields
$doc = NULL
Protected Member Functions
_addButton ($name, $file, $fromSkin=true)
_checkAction ($name)
_createSelect ($name, $label, array $items)
Creates a select menu.
_createThumbnail ($file, $width=100, $height=100)
Creates a thumbnail.
_deleteIcon ($table, $id, $confirmDialog=true, $align= 'bottom')
_editIcon ($table, $id, $align= 'bottom')
_editLink ($table, $uid, $text)
Creates a link to the edit view of a record.
_functionLink ($text, $function)
Creates a link to a function of the menu.
_getActiveMenuItem ()
_getFieldLabel ($table, $field)
Gets the label for a database field.
_getModuleContent (tx_oop_Xhtml_Tag $content)
The method used to get the module content, which has to be declared in the child classes.
_includeJQuery ()
Includes the jQuery JS framework.
_includeJQueryPlugin ($plugin)
Includes a jQuery plugin.
_includeJQueryUi ()
Includes the jQuery UI JS framework.
_includeMootools ()
Includes the Mootools JS framework.
_includePrototype ()
Includes the Prototype JS framework.
_includeScriptaculous ()
Includes the Scriptaculous JS framework.
_includeWebtoolkitScript ($script)
Includes a Webtoolkit script.
_infoIcon ($table, $id, $align= 'bottom')
_link ($text, array $params=array(), $keepModVars=false)
Creates a link with module variables.
_recordIcon ($table, $row, $align= 'bottom')
Gets the CSM menu for a record.
_registerHook ($name, array $params=array())
_setMenuItems (array &$items)
The method used to get the module menu items, which has to be declared in the child classes.
_skinImg ($name, $align= 'bottom')
Gets an icon from the extension.
_t3SkinImg ($name, $align= 'bottom')
Gets an icon from TYPO3.
Protected Attributes
$_backPath = ''
$_lang = NULL
$_modData = NULL
$_modVars = array()
$_pageInfos = array()
Static Protected Attributes
static $_beUser = NULL
A reference to the t3lib_beUserAuth object.
static $_client = array()
A reference to the client informations array.
static $_db = NULL
The instance of the database class (tx_oop_Database_Layer).
static $_str = NULL
The instance of the string utilities class (tx_oop_String_Utils).
static $_t3Conf = array()
A reference to the TYPO3 configuration variables array.
static $_t3Db = NULL
A reference to the t3lib_DB object.
static $_t3Lang = NULL
static $_tca = array()
A reference to the TCA array.
static $_tcaDescr = array()
A reference to the TCA description array.
static $_tce = NULL
The instance of the TCE helper class (tx_oop_Typo3_Core_Engine).
Private Member Functions
_addJs ($path)
Static Private Member Functions
static _setStaticVars ()
Private Attributes
$_buttons
The buttons for the TYPO3 backend module.
$_content = NULL
$_extKey = ''
$_extPath = ''
$_extRelativePath = ''
$_moduleClass = ''
The name of the module (child) class.
$_moduleName = ''
The name of the module.
$_moduleNumber = 0
The module number.
$_modulePath = ''
$_moduleRelativePath = ''
$_moduleSection = ''
The section of the module.
$_pageEnd = ''
$_pageStart = ''
$_reflection = NULL
A reflection object for the backend module.
$_uploadDirectory = ''
Static Private Attributes
static $_hasJQuery = false
Whether the jQuery JS framework has been included.
static $_hasJQueryUi = false
Whether the jQuery UI framework has been included.
static $_hasMootools = false
Whether the Mootools JS framework has been included.
static $_hasPrototype = false
Whether the Prototype JS framework has been included.
static $_hasScriptaculous = false
Whether the Scriptaculous JS framework has been included.
static $_hasStatic = false
A flag to know wether the needed static variables are set.
static $_jQueryLoadedPlugins = array()
The jQuery plugins that have been included.
static $_jQueryPluginsDeps
The dependancies for the jQuery plugins.
static $_oopPath = ''
static $_oopRelativePath = ''
static $_webtoolkitLoadedScripts = array()
The webtoolkit scripts that have been included.
Detailed Description
Definition at line 41 of file Base.class.php.
Constructor & Destructor Documentation
tx_oop_Module_Base::__construct ()
Definition at line 276 of file Base.class.php.
References _setStaticVars(), tx_oop_Session_Data_Backend::getInstance(), and tx_oop_Lang_Getter::getInstance().
Member Function Documentation
tx_oop_Module_Base::__toString ()
Definition at line 327 of file Base.class.php.
tx_oop_Module_Base::_addButton ($ name, $ file, $ fromSkin = true) [protected]
Definition at line 614 of file Base.class.php.
References _skinImg(), and _t3SkinImg().
Referenced by createModulePage().
tx_oop_Module_Base::_addJs ($ path) [private]
Definition at line 377 of file Base.class.php.
Referenced by _includeJQuery(), _includeJQueryPlugin(), _includeJQueryUi(), _includeMootools(), _includePrototype(), _includeScriptaculous(), and _includeWebtoolkitScript().
tx_oop_Module_Base::_checkAction ($ name) [protected]
Definition at line 830 of file Base.class.php.
tx_oop_Module_Base::_createSelect ($ name, $ label, array $ items) [protected]
Creates a select menu.
Parameters:
string The name of the select
string The label for the select menu
array The items to place on the menu, as value/label pairs
Returns:
tx_oop_Xhtml_Tag The select menu
Definition at line 789 of file Base.class.php.
tx_oop_Module_Base::_createThumbnail ($ file, $ width = 100, $ height = 100) [protected]
Creates a thumbnail.
Parameters:
string The file path (relative to the upload directory)
int The thumbnail maximum width
int The thumbnail maximum height
Returns:
tx_oop_Xhtml_Tag The thumbnail picture
Definition at line 411 of file Base.class.php.
tx_oop_Module_Base::_deleteIcon ($ table, $ id, $ confirmDialog = true, $ align = 'bottom') [protected]
Definition at line 721 of file Base.class.php.
tx_oop_Module_Base::_editIcon ($ table, $ id, $ align = 'bottom') [protected]
Definition at line 688 of file Base.class.php.
References _t3SkinImg().
tx_oop_Module_Base::_editLink ($ table, $ uid, $ text) [protected]
Creates a link to the edit view of a record.
Parameters:
string $table The table name
int $uid The ID of the record
string $text The link text
Returns:
tx_oop_Xhtml_Tag The link
Definition at line 512 of file Base.class.php.
tx_oop_Module_Base::_functionLink ($ text, $ function) [protected]
Creates a link to a function of the menu.
Parameters:
string $text The link text
int $function The menu function ID
Returns:
tx_oop_Xhtml_Tag The link
Definition at line 482 of file Base.class.php.
tx_oop_Module_Base::_getActiveMenuItem () [protected]
Definition at line 838 of file Base.class.php.
tx_oop_Module_Base::_getFieldLabel ($ table, $ field) [protected]
Gets the label for a database field.
Parameters:
string The table name
string The field name
Returns:
string The label
Definition at line 752 of file Base.class.php.
tx_oop_Module_Base::_getModuleContent (tx_oop_Xhtml_Tag $ content) [abstract, protected]
The method used to get the module content, which has to be declared in the child classes.
Referenced by createModulePage().
tx_oop_Module_Base::_includeJQuery () [protected]
Includes the jQuery JS framework.
Returns:
NULL
Definition at line 848 of file Base.class.php.
References _addJs().
tx_oop_Module_Base::_includeJQueryPlugin ($ plugin) [protected]
Includes a jQuery plugin.
Available plugins are:
accordion
dimensions
Parameters:
string The name of the plugin to include
Returns:
NULL
Definition at line 975 of file Base.class.php.
References _addJs().
tx_oop_Module_Base::_includeJQueryUi () [protected]
Includes the jQuery UI JS framework.
Returns:
NULL
Definition at line 866 of file Base.class.php.
References _addJs().
tx_oop_Module_Base::_includeMootools () [protected]
Includes the Mootools JS framework.
Returns:
NULL
Definition at line 884 of file Base.class.php.
References _addJs().
tx_oop_Module_Base::_includePrototype () [protected]
Includes the Prototype JS framework.
Returns:
NULL
Definition at line 902 of file Base.class.php.
References _addJs().
Referenced by _includeScriptaculous().
tx_oop_Module_Base::_includeScriptaculous () [protected]
Includes the Scriptaculous JS framework.
Returns:
NULL
See also:
_includePrototype
Definition at line 921 of file Base.class.php.
References _addJs(), and _includePrototype().
tx_oop_Module_Base::_includeWebtoolkitScript ($ script) [protected]
Includes a Webtoolkit script.
Available scripts are:
base64
crc32
md5
sha1
sha256
url
utf8
Parameters:
string The name of the script to include
Returns:
NULL
Definition at line 952 of file Base.class.php.
References _addJs().
tx_oop_Module_Base::_infoIcon ($ table, $ id, $ align = 'bottom') [protected]
Definition at line 705 of file Base.class.php.
References _t3SkinImg().
tx_oop_Module_Base::_link ($ text, array $ params = array(), $ keepModVars = false) [protected]
Creates a link with module variables.
Parameters:
string The link text
array The module variables to set, as key/value pairs
array The module variables to keep
Returns:
tx_oop_Xhtml_Tag The link
Definition at line 452 of file Base.class.php.
tx_oop_Module_Base::_recordIcon ($ table, $ row, $ align = 'bottom') [protected]
Gets the CSM menu for a record.
This method creates an icon of the requested record with a Context Sensitive Menu (CSM).
Parameters:
string The table of the record
array The record's row
array The align parameter of the IMG tag
Returns:
tx_oop_Xhtml_Tag The icon with a CSM menu link
Definition at line 644 of file Base.class.php.
tx_oop_Module_Base::_registerHook ($ name, array $ params = array()) [protected]
Definition at line 390 of file Base.class.php.
tx_oop_Module_Base::_setMenuItems (array &$ items) [abstract, protected]
The method used to get the module menu items, which has to be declared in the child classes.
Referenced by menuConfig().
static tx_oop_Module_Base::_setStaticVars () [static, private]
Definition at line 357 of file Base.class.php.
References tx_oop_Typo3_Core_Engine::getInstance(), tx_oop_String_Utils::getInstance(), and tx_oop_Database_Layer::getInstance().
Referenced by __construct().
tx_oop_Module_Base::_skinImg ($ name, $ align = 'bottom') [protected]
Gets an icon from the extension.
Parameters:
string $name The icon name
array The align parameter of the IMG tag
Returns:
tx_oop_Xhtml_Tag The image tag
Definition at line 539 of file Base.class.php.
Referenced by _addButton().
tx_oop_Module_Base::_t3SkinImg ($ name, $ align = 'bottom') [protected]
Gets an icon from TYPO3.
Parameters:
string $name The icon name
array The align parameter of the IMG tag
Returns:
tx_oop_Xhtml_Tag The image tag
Definition at line 578 of file Base.class.php.
Referenced by _addButton(), _editIcon(), and _infoIcon().
tx_oop_Module_Base::createModulePage ()
Definition at line 1016 of file Base.class.php.
References _addButton(), and _getModuleContent().
tx_oop_Module_Base::menuConfig ()
Definition at line 1002 of file Base.class.php.
References _setMenuItems().
Field Documentation
tx_oop_Module_Base::$_backPath = '' [protected]
Definition at line 266 of file Base.class.php.
tx_oop_Module_Base::$_beUser = NULL [static, protected]
A reference to the t3lib_beUserAuth object.
Definition at line 142 of file Base.class.php.
tx_oop_Module_Base::$_buttons [private]
Initial value:
 array(
        'csh'      => '',
        'save'     => '',
        'shortcut' => ''
    )
The buttons for the TYPO3 backend module.
Definition at line 182 of file Base.class.php.
tx_oop_Module_Base::$_client = array() [static, protected]
A reference to the client informations array.
Definition at line 157 of file Base.class.php.
tx_oop_Module_Base::$_content = NULL [private]
Definition at line 177 of file Base.class.php.
tx_oop_Module_Base::$_db = NULL [static, protected]
The instance of the database class (tx_oop_Database_Layer).
Definition at line 117 of file Base.class.php.
tx_oop_Module_Base::$_extKey = '' [private]
Definition at line 221 of file Base.class.php.
tx_oop_Module_Base::$_extPath = '' [private]
Definition at line 226 of file Base.class.php.
tx_oop_Module_Base::$_extRelativePath = '' [private]
Definition at line 231 of file Base.class.php.
tx_oop_Module_Base::$_hasJQuery = false [static, private]
Whether the jQuery JS framework has been included.
Definition at line 73 of file Base.class.php.
tx_oop_Module_Base::$_hasJQueryUi = false [static, private]
Whether the jQuery UI framework has been included.
Definition at line 78 of file Base.class.php.
tx_oop_Module_Base::$_hasMootools = false [static, private]
Whether the Mootools JS framework has been included.
Definition at line 83 of file Base.class.php.
tx_oop_Module_Base::$_hasPrototype = false [static, private]
Whether the Prototype JS framework has been included.
Definition at line 88 of file Base.class.php.
tx_oop_Module_Base::$_hasScriptaculous = false [static, private]
Whether the Scriptaculous JS framework has been included.
Definition at line 93 of file Base.class.php.
tx_oop_Module_Base::$_hasStatic = false [static, private]
A flag to know wether the needed static variables are set.
Definition at line 58 of file Base.class.php.
tx_oop_Module_Base::$_jQueryLoadedPlugins = array() [static, private]
The jQuery plugins that have been included.
Definition at line 103 of file Base.class.php.
tx_oop_Module_Base::$_jQueryPluginsDeps [static, private]
Initial value:
 array(
        'accordion' => array(
            'dimensions'
        )
    )
The dependancies for the jQuery plugins.
Definition at line 108 of file Base.class.php.
tx_oop_Module_Base::$_lang = NULL [protected]
Definition at line 167 of file Base.class.php.
tx_oop_Module_Base::$_modData = NULL [protected]
Definition at line 261 of file Base.class.php.
tx_oop_Module_Base::$_moduleClass = '' [private]
The name of the module (child) class.
Definition at line 196 of file Base.class.php.
tx_oop_Module_Base::$_moduleName = '' [private]
The name of the module.
Definition at line 201 of file Base.class.php.
tx_oop_Module_Base::$_moduleNumber = 0 [private]
The module number.
Definition at line 191 of file Base.class.php.
tx_oop_Module_Base::$_modulePath = '' [private]
Definition at line 211 of file Base.class.php.
tx_oop_Module_Base::$_moduleRelativePath = '' [private]
Definition at line 216 of file Base.class.php.
tx_oop_Module_Base::$_moduleSection = '' [private]
The section of the module.
Definition at line 206 of file Base.class.php.
tx_oop_Module_Base::$_modVars = array() [protected]
Definition at line 256 of file Base.class.php.
tx_oop_Module_Base::$_oopPath = '' [static, private]
Definition at line 63 of file Base.class.php.
tx_oop_Module_Base::$_oopRelativePath = '' [static, private]
Definition at line 68 of file Base.class.php.
tx_oop_Module_Base::$_pageEnd = '' [private]
Definition at line 246 of file Base.class.php.
tx_oop_Module_Base::$_pageInfos = array() [protected]
Definition at line 251 of file Base.class.php.
tx_oop_Module_Base::$_pageStart = '' [private]
Definition at line 241 of file Base.class.php.
tx_oop_Module_Base::$_reflection = NULL [private]
A reflection object for the backend module.
Definition at line 172 of file Base.class.php.
tx_oop_Module_Base::$_str = NULL [static, protected]
The instance of the string utilities class (tx_oop_String_Utils).
Definition at line 122 of file Base.class.php.
tx_oop_Module_Base::$_t3Conf = array() [static, protected]
A reference to the TYPO3 configuration variables array.
Definition at line 162 of file Base.class.php.
tx_oop_Module_Base::$_t3Db = NULL [static, protected]
A reference to the t3lib_DB object.
Definition at line 132 of file Base.class.php.
tx_oop_Module_Base::$_t3Lang = NULL [static, protected]
Definition at line 137 of file Base.class.php.
tx_oop_Module_Base::$_tca = array() [static, protected]
A reference to the TCA array.
Definition at line 152 of file Base.class.php.
tx_oop_Module_Base::$_tcaDescr = array() [static, protected]
A reference to the TCA description array.
Definition at line 147 of file Base.class.php.
tx_oop_Module_Base::$_tce = NULL [static, protected]
The instance of the TCE helper class (tx_oop_Typo3_Core_Engine).
Definition at line 127 of file Base.class.php.
tx_oop_Module_Base::$_uploadDirectory = '' [private]
Definition at line 236 of file Base.class.php.
tx_oop_Module_Base::$_webtoolkitLoadedScripts = array() [static, private]
The webtoolkit scripts that have been included.
Definition at line 98 of file Base.class.php.
tx_oop_Module_Base::$doc = NULL
Definition at line 271 of file Base.class.php.
The documentation for this class was generated from the following file:
tx/oop/Module/Base.class.php