TYPO3-OOP: tx_oop_Flexform_Field_Section Class Reference
tx_oop_Flexform_Field_Section Class Reference
Detailed Description
Definition at line 38 of file Section.class.php.
Public Member Functions
__get ($name)
__isset ($name)
__set ($name, $value)
__unset ($name)
addElement ($name)
Adds an element to the section.
addFieldXmlObject (SimpleXMLElement $el)
getElement ($name)
Gets a element from the section.
Protected Member Functions
_writeConfigObject (array $configSection, SimpleXMLElement $xml)
Protected Attributes
$_config = array()
The properties of config section of the field.
$_elements = array()
The elements (types) of the section.
$_fieldType = 'array'
The type of the field.
$_langFile = ''
The file with the language labels.
$_name = ''
The name of the field.
$_properties = array()
The properties of the field.
$_sheetName = ''
The name of the sheet.
Member Function Documentation
tx_oop_Flexform_Field::__get ($ name) [inherited]
Definition at line 99 of file Field.class.php.
tx_oop_Flexform_Field::__isset ($ name) [inherited]
Definition at line 149 of file Field.class.php.
tx_oop_Flexform_Field::__set ($ name, $ value) [inherited]
Definition at line 124 of file Field.class.php.
tx_oop_Flexform_Field::__unset ($ name) [inherited]
Definition at line 173 of file Field.class.php.
tx_oop_Flexform_Field::_writeConfigObject (array $ configSection, SimpleXMLElement $ xml) [protected, inherited]
Definition at line 197 of file Field.class.php.
Referenced by tx_oop_Flexform_Field::addFieldXmlObject().
tx_oop_Flexform_Field_Section::addElement ($ name)
Adds an element to the section.
Parameters:
string The name of the element
Returns:
tx_oop_Flexform_Field_Section_Element The flexform section element object
Exceptions:
tx_oop_Flexform_Field_Section_Exception If the element already exists
Definition at line 79 of file Section.class.php.
References getElement().
tx_oop_Flexform_Field_Section::addFieldXmlObject (SimpleXMLElement $ el)
Reimplemented from tx_oop_Flexform_Field.
Definition at line 53 of file Section.class.php.
tx_oop_Flexform_Field_Section::getElement ($ name)
Gets a element from the section.
Parameters:
string The name of the element
Returns:
tx_oop_Flexform_Field_Section_Element The flexform section element object
Exceptions:
tx_oop_Flexform_Field_Section_Exception If the element does not exists
Definition at line 105 of file Section.class.php.
Referenced by addElement().
Field Documentation
tx_oop_Flexform_Field::$_config = array() [protected, inherited]
The properties of config section of the field.
Definition at line 68 of file Field.class.php.
tx_oop_Flexform_Field_Section::$_elements = array() [protected]
The elements (types) of the section.
Definition at line 48 of file Section.class.php.
tx_oop_Flexform_Field_Section::$_fieldType = 'array' [protected]
The type of the field.
Reimplemented from tx_oop_Flexform_Field.
Definition at line 43 of file Section.class.php.
tx_oop_Flexform_Field::$_langFile = '' [protected, inherited]
The file with the language labels.
Definition at line 58 of file Field.class.php.
tx_oop_Flexform_Field::$_name = '' [protected, inherited]
The name of the field.
Definition at line 48 of file Field.class.php.
tx_oop_Flexform_Field::$_properties = array() [protected, inherited]
The properties of the field.
Definition at line 63 of file Field.class.php.
tx_oop_Flexform_Field::$_sheetName = '' [protected, inherited]
The name of the sheet.
Definition at line 53 of file Field.class.php.
The documentation for this class was generated from the following file:
tx/oop/Flexform/Field/Section.class.php