TYPO3-OOP: tx_oop_Tca_Table Class Reference
tx_oop_Tca_Table Class Reference
Detailed Description
Definition at line 53 of file Table.class.php.
Public Member Functions
__get ($name)
Gets a property of the table control section.
__isset ($name)
Checks if a property of the table control section exists.
__set ($name, $value)
Sets a property of the table control section.
__toString ()
Converts the TCA table object to a serialized array.
__unset ($name)
Removes a property of the table control section.
addEndTimeField ($name= 'endtime')
Adds the 'endtime' field.
addFeUserGroupField ($name= 'fe_group')
Adds the 'fe_group' field.
addField ($name, $type)
Adds a field for the current instance (table).
addHiddenField ($checked=false, $name= 'hidden')
Adds the 'hidden' field.
addStartTimeField ($name= 'starttime')
Adds the 'starttime' field.
enableLocalization ($languageField= 'sys_language_uid', $origPointerField= 'l10n_parent', $diffSourceField= 'l10n_diffsource')
enableVersionning ($origUid= 't3_origuid')
getExtensionKey ()
Gets the full table name for the current instance.
getField ($name)
Gets a specific field.
getTableName ()
Gets the full table name for the current instance.
setDefaultSortBy ($name, $desc=false)
Sets the default 'SORT BY' clause for current instance (table).
& storeToTca ()
Stores the current TCA object to the TYPO3 TCA array.
toArray ()
Converts the current TCA object to an array, for use with TYPO3.
Static Public Member Functions
static getInstance ($extKey, $name)
Gets an instance of a TCA table.
Private Member Functions
__construct ($extKey, $tableName)
Class constructor.
_addField ($name, $type)
Adds a field for the current instance (table).
Private Attributes
$_ctrl = array()
The properties of the TCA control section.
$_extKey = ''
The extension key.
$_extPath = ''
The extension path (absolute).
$_extRelPath = ''
The extension path (relative).
$_fields = array()
The TCA fields (instances of tx_oop_Tca_Field).
$_instanceName = ''
The instance (table) name.
$_userFields = array()
The name of the user fields (not TYPO3 control fields).
Static Private Attributes
static $_instances = array()
An array with the TCA table instances.
static $_nbInstances = 0
The number of instances.
static $_reserved
Reserved field names.
Constructor & Destructor Documentation
tx_oop_Tca_Table::__construct ($ extKey, $ tableName) [private]
Class constructor.
Parameters:
string The extension key
string The full table name
Returns:
NULL
Definition at line 234 of file Table.class.php.
References setDefaultSortBy().
Member Function Documentation
tx_oop_Tca_Table::__get ($ name)
Gets a property of the table control section.
Parameters:
string The name of the property
Returns:
mixed The value of the property
Definition at line 289 of file Table.class.php.
tx_oop_Tca_Table::__isset ($ name)
Checks if a property of the table control section exists.
Parameters:
string The name of the property
Returns:
boolean Wheter the property is defined
Definition at line 320 of file Table.class.php.
tx_oop_Tca_Table::__set ($ name, $ value)
Sets a property of the table control section.
Parameters:
string The name of the property
mixed The value of the property
Returns:
NULL
Definition at line 309 of file Table.class.php.
tx_oop_Tca_Table::__toString ()
Converts the TCA table object to a serialized array.
Returns:
string The serialized array
Definition at line 341 of file Table.class.php.
References toArray().
tx_oop_Tca_Table::__unset ($ name)
Removes a property of the table control section.
Parameters:
string The name of the property
Returns:
NULL
Definition at line 331 of file Table.class.php.
tx_oop_Tca_Table::_addField ($ name, $ type) [private]
Adds a field for the current instance (table).
Parameters:
string The name of the field
string The type of the field (see TYPO3 Core API, TCA section)
Returns:
tx_oop_Tca_Field The TCA field instance
Exceptions:
tx_oop_Tca_Table_Exception If the field type is invalid
Definition at line 384 of file Table.class.php.
tx_oop_Tca_Table::addEndTimeField ($ name = 'endtime')
Adds the 'endtime' field.
Parameters:
string The name of the field (default is 'endtime')
Returns:
tx_oop_Tca_Field_Input The 'endtime' field object
Definition at line 653 of file Table.class.php.
tx_oop_Tca_Table::addFeUserGroupField ($ name = 'fe_group')
Adds the 'fe_group' field.
Parameters:
string The name of the field (default is 'fe_group')
Returns:
tx_oop_Tca_Field_Select The 'fe_group' field object
Definition at line 708 of file Table.class.php.
tx_oop_Tca_Table::addField ($ name, $ type)
Adds a field for the current instance (table).
Parameters:
string The name of the field
string The type of the field (see TYPO3 Core API, TCA section)
Returns:
tx_oop_Tca_Field The TCA field instance
Exceptions:
tx_oop_Tca_Table_Exception If the field name is reserved
tx_oop_Tca_Table_Exception If the field already exists
Definition at line 493 of file Table.class.php.
tx_oop_Tca_Table::addHiddenField ($ checked = false, $ name = 'hidden')
Adds the 'hidden' field.
Parameters:
boolean Wheter the checkbox is checked by default or not
string The name of the field (default is 'hidden')
Returns:
tx_oop_Tca_Field_Check The 'hidden' field object
Definition at line 567 of file Table.class.php.
tx_oop_Tca_Table::addStartTimeField ($ name = 'starttime')
Adds the 'starttime' field.
Parameters:
string The name of the field (default is 'starttime')
Returns:
tx_oop_Tca_Field_Input The 'starttime' field object
Definition at line 607 of file Table.class.php.
tx_oop_Tca_Table::enableLocalization ($ languageField = 'sys_language_uid', $ origPointerField = 'l10n_parent', $ diffSourceField = 'l10n_diffsource')
Definition at line 765 of file Table.class.php.
tx_oop_Tca_Table::enableVersionning ($ origUid = 't3_origuid')
Definition at line 751 of file Table.class.php.
tx_oop_Tca_Table::getExtensionKey ()
Gets the full table name for the current instance.
Returns:
string The full table name
Definition at line 479 of file Table.class.php.
Referenced by tx_oop_Tca_Field::__construct().
tx_oop_Tca_Table::getField ($ name)
Gets a specific field.
Returns:
tx_oop_Tca_Field The requested field
Exceptions:
tx_oop_Tca_Table_Exception If the field does not exist
Definition at line 544 of file Table.class.php.
static tx_oop_Tca_Table::getInstance ($ extKey, $ name) [static]
Gets an instance of a TCA table.
If the specified instance does not exist, this method will create it, and then return it.
Parameters:
string The extension key
string The short name name of the table (will be prepended with the extension key, in accordance to the TYPO3 coding guidelines)
Returns:
tx_oop_Tca_Table The instance of the TCA table
Definition at line 356 of file Table.class.php.
tx_oop_Tca_Table::getTableName ()
Gets the full table name for the current instance.
Returns:
string The full table name
Definition at line 469 of file Table.class.php.
tx_oop_Tca_Table::setDefaultSortBy ($ name, $ desc = false)
Sets the default 'SORT BY' clause for current instance (table).
Parameters:
string The name of the sort field
boolean True if the sort is descending, otherwise false
Returns:
NULL
Definition at line 533 of file Table.class.php.
Referenced by __construct().
& tx_oop_Tca_Table::storeToTca ()
Stores the current TCA object to the TYPO3 TCA array.
Returns:
array The TCA array for the current instance (by reference)
Definition at line 455 of file Table.class.php.
tx_oop_Tca_Table::toArray ()
Converts the current TCA object to an array, for use with TYPO3.
Returns:
array The TCA array for the current instance
Definition at line 428 of file Table.class.php.
Referenced by __toString().
Field Documentation
tx_oop_Tca_Table::$_ctrl = array() [private]
The properties of the TCA control section.
Definition at line 215 of file Table.class.php.
tx_oop_Tca_Table::$_extKey = '' [private]
The extension key.
Definition at line 200 of file Table.class.php.
tx_oop_Tca_Table::$_extPath = '' [private]
The extension path (absolute).
Definition at line 205 of file Table.class.php.
tx_oop_Tca_Table::$_extRelPath = '' [private]
The extension path (relative).
Definition at line 210 of file Table.class.php.
tx_oop_Tca_Table::$_fields = array() [private]
The TCA fields (instances of tx_oop_Tca_Field).
Definition at line 220 of file Table.class.php.
tx_oop_Tca_Table::$_instanceName = '' [private]
The instance (table) name.
Definition at line 195 of file Table.class.php.
tx_oop_Tca_Table::$_instances = array() [static, private]
An array with the TCA table instances.
Definition at line 58 of file Table.class.php.
tx_oop_Tca_Table::$_nbInstances = 0 [static, private]
The number of instances.
Definition at line 63 of file Table.class.php.
tx_oop_Tca_Table::$_reserved [static, private]
Reserved field names.
Definition at line 68 of file Table.class.php.
tx_oop_Tca_Table::$_userFields = array() [private]
The name of the user fields (not TYPO3 control fields).
Definition at line 225 of file Table.class.php.
The documentation for this class was generated from the following file:
tx/oop/Tca/Table.class.php