TYPO3-OOP: tx_oop_Debug_Utils Class Reference
tx_oop_Debug_Utils Class Reference
Public Member Functions
debug ($var, $return=false, $header= 'Debug informations')
Static Public Member Functions
static viewArray (array $array, $return=false)
Private Member Functions
__construct ()
Static Private Member Functions
static _getVarType (&$var)
Detailed Description
Definition at line 38 of file Utils.class.php.
Constructor & Destructor Documentation
tx_oop_Debug_Utils::__construct () [private]
Definition at line 43 of file Utils.class.php.
Member Function Documentation
static tx_oop_Debug_Utils::_getVarType (&$ var) [static, private]
Definition at line 49 of file Utils.class.php.
Referenced by debug(), and viewArray().
tx_oop_Debug_Utils::debug ($ var, $ return = false, $ header = 'Debug informations')
Definition at line 158 of file Utils.class.php.
References _getVarType().
static tx_oop_Debug_Utils::viewArray (array $ array, $ return = false) [static]
Definition at line 96 of file Utils.class.php.
References _getVarType().
The documentation for this class was generated from the following file:
tx/oop/Debug/Utils.class.php