TYPO3-OOP: tx_oop_Flexform_Iterator Class Reference
tx_oop_Flexform_Iterator Class Reference
Detailed Description
Definition at line 38 of file Iterator.class.php.
Public Member Functions
__construct (&$xmlData, $itemType= '')
Class constructor.
__get ($fieldName)
PHP getter method.
__toString ()
PHP toString method.
current ()
Get current element (Iterator method).
getFieldValue ($fieldName, $sheet= 'sDEF', $lang= 'lDEF', $value= 'vDEF')
Gets the value of a flexform field.
key ()
Get current element's key (Iterator method).
next ()
Move position to the next element (Iterator method).
rewind ()
Move position to the first element (Iterator method).
setDefaultLang ($id)
Sets the default flexform lang ID.
setDefaultSheet ($id)
Sets the default flexform sheet ID.
setDefaultValue ($id)
Sets the default flexform value ID.
valid ()
Checks current element (Iterator method).
Protected Member Functions
_getFieldsShortcut ()
Gets a shorctut to the fields object.
Protected Attributes
$_fields = NULL
Shortcut for the flexform fields.
$_flexData = NULL
SimpleXMLElement with the data from the flexform.
$_itemType = ''
The items type for a flexform section.
$_iteratorIndex = 0
Current position for the iterator methods.
$_lang = 'lDEF'
Default ID for the flexform language section, for the __get method.
$_sheet = 'sDEF'
Default ID for the flexform sheet section, for the __get method.
$_subObject = false
Current instance is for a flexform section.
$_value = 'vDEF'
Default ID for the flexform value section, for the __get method.
Constructor & Destructor Documentation
tx_oop_Flexform_Iterator::__construct (&$ xmlData, $ itemType = '')
Class constructor.
Parameters:
string The flexform XML data
Returns:
NULL
Definition at line 86 of file Iterator.class.php.
References _getFieldsShortcut(), and tx_oop_Flexform_Iterator_Exception::EXCEPTION_BAD_XML.
Member Function Documentation
tx_oop_Flexform_Iterator::__get ($ fieldName)
PHP getter method.
This methods gets the value of a flexform field, as if it was a property of this class.
Parameters:
string The name of the flexform field
Returns:
string The field value
Definition at line 130 of file Iterator.class.php.
References getFieldValue().
tx_oop_Flexform_Iterator::__toString ()
PHP toString method.
Returns:
string A blank string or the item type, if used in a flexform section
Definition at line 146 of file Iterator.class.php.
tx_oop_Flexform_Iterator::_getFieldsShortcut () [protected]
Gets a shorctut to the fields object.
Returns:
boolean
Definition at line 235 of file Iterator.class.php.
Referenced by __construct(), setDefaultLang(), and setDefaultSheet().
tx_oop_Flexform_Iterator::current ()
Get current element (Iterator method).
Returns:
SimpleXML The current XML object
Definition at line 166 of file Iterator.class.php.
tx_oop_Flexform_Iterator::getFieldValue ($ fieldName, $ sheet = 'sDEF', $ lang = 'lDEF', $ value = 'vDEF')
Gets the value of a flexform field.
Parameters:
string The name of the flexform field
string The ID of the flexform sheet (default is sDEF)
string The ID of the language (default is lDEF)
string The ID of the value (default is vDEF)
Returns:
string The value of the flexform field
Definition at line 266 of file Iterator.class.php.
Referenced by __get().
tx_oop_Flexform_Iterator::key ()
Get current element's key (Iterator method).
Returns:
int The name of the current XML tag
Definition at line 204 of file Iterator.class.php.
tx_oop_Flexform_Iterator::next ()
Move position to the next element (Iterator method).
Returns:
NULL
Definition at line 215 of file Iterator.class.php.
tx_oop_Flexform_Iterator::rewind ()
Move position to the first element (Iterator method).
Returns:
NULL
Definition at line 156 of file Iterator.class.php.
tx_oop_Flexform_Iterator::setDefaultLang ($ id)
Sets the default flexform lang ID.
Parameters:
string The ID of the lang
Returns:
boolean
Definition at line 365 of file Iterator.class.php.
References _getFieldsShortcut().
tx_oop_Flexform_Iterator::setDefaultSheet ($ id)
Sets the default flexform sheet ID.
Parameters:
string The ID of the sheet
Returns:
boolean
Definition at line 342 of file Iterator.class.php.
References _getFieldsShortcut().
tx_oop_Flexform_Iterator::setDefaultValue ($ id)
Sets the default flexform value ID.
Parameters:
string The ID of the value
Returns:
boolean
Definition at line 387 of file Iterator.class.php.
tx_oop_Flexform_Iterator::valid ()
Checks current element (Iterator method).
Returns:
boolean
Definition at line 225 of file Iterator.class.php.
Field Documentation
tx_oop_Flexform_Iterator::$_fields = NULL [protected]
Shortcut for the flexform fields.
Definition at line 48 of file Iterator.class.php.
tx_oop_Flexform_Iterator::$_flexData = NULL [protected]
SimpleXMLElement with the data from the flexform.
Definition at line 43 of file Iterator.class.php.
tx_oop_Flexform_Iterator::$_itemType = '' [protected]
The items type for a flexform section.
Definition at line 78 of file Iterator.class.php.
tx_oop_Flexform_Iterator::$_iteratorIndex = 0 [protected]
Current position for the iterator methods.
Definition at line 68 of file Iterator.class.php.
tx_oop_Flexform_Iterator::$_lang = 'lDEF' [protected]
Default ID for the flexform language section, for the __get method.
Definition at line 58 of file Iterator.class.php.
tx_oop_Flexform_Iterator::$_sheet = 'sDEF' [protected]
Default ID for the flexform sheet section, for the __get method.
Definition at line 53 of file Iterator.class.php.
tx_oop_Flexform_Iterator::$_subObject = false [protected]
Current instance is for a flexform section.
Definition at line 73 of file Iterator.class.php.
tx_oop_Flexform_Iterator::$_value = 'vDEF' [protected]
Default ID for the flexform value section, for the __get method.
Definition at line 63 of file Iterator.class.php.
The documentation for this class was generated from the following file:
tx/oop/Flexform/Iterator.class.php