TYPO3-OOP: tx_oop_Flexform_Builder Class Reference
tx_oop_Flexform_Builder Class Reference
Detailed Description
Definition at line 38 of file Builder.class.php.
Public Member Functions
__construct ($langFile, $langDisable=true, $langChildren=false)
Class constructor.
__toString ()
Converts the flexform object to an XML string.
addSheet ($name)
Adds a sheet to the flexform.
createXmlObject ()
Gets the flexform as a simple XML object.
getSheet ($name)
Gets a flexform sheet.
setLangChildren ($value)
Decides wheter the localizations are bound to the defaut values.
setLangDisable ($value)
Decides wheter to disable the handling of localizations.
Protected Attributes
$_langChildren = false
Wheter the localizations are bound to the defaut values.
$_langDisable = true
Wheter to disable the handling of localizations.
$_langFile = ''
The file with the language labels.
$_sheets = array()
An array with the flexform sheets.
Constructor & Destructor Documentation
tx_oop_Flexform_Builder::__construct ($ langFile, $ langDisable = true, $ langChildren = false)
Class constructor.
Parameters:
string The reference of the file with the labels for the flexform (typically: EXT:extkey/path/to/lang/file)
boolean Wheter to disable the handling of localizations
boolean Wheter the localizations are bound to the defaut values
Returns:
NULL
Definition at line 68 of file Builder.class.php.
Member Function Documentation
tx_oop_Flexform_Builder::__toString ()
Converts the flexform object to an XML string.
Returns:
string The XML for the flexform
Definition at line 80 of file Builder.class.php.
References createXmlObject().
tx_oop_Flexform_Builder::addSheet ($ name)
Adds a sheet to the flexform.
Parameters:
string The name of the sheet
Returns:
tx_oop_Flexform_Sheet The sheet object
Exceptions:
tx_oop_Flexform_Builder_Exception If the sheet already exists
Definition at line 124 of file Builder.class.php.
References getSheet().
tx_oop_Flexform_Builder::createXmlObject ()
Gets the flexform as a simple XML object.
Returns:
SimpleXMLElement The flexform XML object
Definition at line 94 of file Builder.class.php.
Referenced by __toString().
tx_oop_Flexform_Builder::getSheet ($ name)
Gets a flexform sheet.
Parameters:
string The name of the sheet
Returns:
tx_oop_Flexform_Sheet The sheet object
Exceptions:
tx_oop_Flexform_Builder_Exception If the sheet does not exist
Definition at line 150 of file Builder.class.php.
Referenced by addSheet().
tx_oop_Flexform_Builder::setLangChildren ($ value)
Decides wheter the localizations are bound to the defaut values.
Parameters:
boolean If true, the localizations will be bound to the defaut values
Returns:
NULL
Definition at line 183 of file Builder.class.php.
tx_oop_Flexform_Builder::setLangDisable ($ value)
Decides wheter to disable the handling of localizations.
Parameters:
boolean If true, the handling of localizations will be disabled
Returns:
NULL
Definition at line 172 of file Builder.class.php.
Field Documentation
tx_oop_Flexform_Builder::$_langChildren = false [protected]
Wheter the localizations are bound to the defaut values.
Definition at line 53 of file Builder.class.php.
tx_oop_Flexform_Builder::$_langDisable = true [protected]
Wheter to disable the handling of localizations.
Definition at line 48 of file Builder.class.php.
tx_oop_Flexform_Builder::$_langFile = '' [protected]
The file with the language labels.
Definition at line 58 of file Builder.class.php.
tx_oop_Flexform_Builder::$_sheets = array() [protected]
An array with the flexform sheets.
Definition at line 43 of file Builder.class.php.
The documentation for this class was generated from the following file:
tx/oop/Flexform/Builder.class.php