TYPO3-OOP: tx_oop_Session_Data_Backend Class Reference
tx_oop_Session_Data_Backend Class Reference
Public Member Functions
__get ($name)
__isset ($name)
__set ($name, $value)
__toString ()
__unset ($name)
current ()
key ()
next ()
offsetExists ($name)
offsetGet ($name)
offsetSet ($name, $value)
offsetUnset ($name)
rewind ()
valid ()
Static Public Member Functions
static getInstance ($name)
Protected Member Functions
_getSessionData ()
_getUser ()
_updateSessionData ()
Static Protected Member Functions
static _getInstance ($class, $name)
Protected Attributes
$_data = array()
$_instanceName = ''
$_user = NULL
Detailed Description
Definition at line 38 of file Backend.class.php.
Member Function Documentation
tx_oop_Session_Data_Base::__get ($ name) [inherited]
Definition at line 116 of file Base.class.php.
tx_oop_Session_Data_Base::__isset ($ name) [inherited]
Definition at line 133 of file Base.class.php.
tx_oop_Session_Data_Base::__set ($ name, $ value) [inherited]
Definition at line 124 of file Base.class.php.
References tx_oop_Session_Data_Base::_updateSessionData().
tx_oop_Session_Data_Base::__toString () [inherited]
Definition at line 108 of file Base.class.php.
tx_oop_Session_Data_Base::__unset ($ name) [inherited]
Definition at line 141 of file Base.class.php.
References tx_oop_Session_Data_Base::_updateSessionData().
static tx_oop_Session_Data_Base::_getInstance ($ class, $ name) [static, protected, inherited]
Definition at line 225 of file Base.class.php.
Referenced by tx_oop_Session_Data_Frontend::getInstance(), and getInstance().
tx_oop_Session_Data_Backend::_getSessionData () [protected]
Reimplemented from tx_oop_Session_Data_Base.
Definition at line 62 of file Backend.class.php.
tx_oop_Session_Data_Backend::_getUser () [protected]
Reimplemented from tx_oop_Session_Data_Base.
Definition at line 54 of file Backend.class.php.
tx_oop_Session_Data_Backend::_updateSessionData () [protected]
Reimplemented from tx_oop_Session_Data_Base.
Definition at line 70 of file Backend.class.php.
tx_oop_Session_Data_Base::current () [inherited]
Definition at line 192 of file Base.class.php.
static tx_oop_Session_Data_Backend::getInstance ($ name) [static]
Reimplemented from tx_oop_Session_Data_Base.
Definition at line 43 of file Backend.class.php.
References tx_oop_Session_Data_Base::_getInstance().
Referenced by tx_oop_Module_Base::__construct().
tx_oop_Session_Data_Base::key () [inherited]
Definition at line 184 of file Base.class.php.
tx_oop_Session_Data_Base::next () [inherited]
Definition at line 200 of file Base.class.php.
tx_oop_Session_Data_Base::offsetExists ($ name) [inherited]
Definition at line 167 of file Base.class.php.
tx_oop_Session_Data_Base::offsetGet ($ name) [inherited]
Definition at line 150 of file Base.class.php.
tx_oop_Session_Data_Base::offsetSet ($ name, $ value) [inherited]
Definition at line 158 of file Base.class.php.
References tx_oop_Session_Data_Base::_updateSessionData().
tx_oop_Session_Data_Base::offsetUnset ($ name) [inherited]
Definition at line 175 of file Base.class.php.
References tx_oop_Session_Data_Base::_updateSessionData().
tx_oop_Session_Data_Base::rewind () [inherited]
Definition at line 217 of file Base.class.php.
tx_oop_Session_Data_Base::valid () [inherited]
Definition at line 209 of file Base.class.php.
Field Documentation
tx_oop_Session_Data_Base::$_data = array() [protected, inherited]
Definition at line 88 of file Base.class.php.
tx_oop_Session_Data_Base::$_instanceName = '' [protected, inherited]
Definition at line 83 of file Base.class.php.
tx_oop_Session_Data_Base::$_user = NULL [protected, inherited]
Definition at line 78 of file Base.class.php.
The documentation for this class was generated from the following file:
tx/oop/Session/Data/Backend.class.php