TYPO3-OOP: tx_oop_Frontend_Template Class Reference
tx_oop_Frontend_Template Class Reference
Public Member Functions
__construct (tslib_cObj $cObj, $templateFilePath)
Class constructor.
__get ($name)
__isset ($name)
__set ($name, $value)
__toString ()
__unset ($name)
offsetExists ($name)
offsetGet ($name)
offsetSet ($name, $value)
offsetUnset ($name)
Protected Member Functions
_initTemplate ($templateFilePath)
Loads a template file.
Protected Attributes
$_cObj = NULL
The instance of the tslib_cObj class.
$_sections = array()
The template sections.
$_templateContent = NULL
The template resource.
Static Protected Attributes
static $_str = NULL
The instance of the string utilities class (tx_oop_String_Utils).
Static Private Member Functions
static _setStaticVars ()
Static Private Attributes
static $_hasStatic = false
A flag to know wether the needed static variables are set.
Detailed Description
Definition at line 38 of file Template.class.php.
Constructor & Destructor Documentation
tx_oop_Frontend_Template::__construct (tslib_cObj $ cObj, $ templateFilePath)
Class constructor.
Parameters:
tslib_cObj The instance of tslib_cObj
string The path to the template file
Returns:
NULL
Definition at line 72 of file Template.class.php.
References _initTemplate(), and _setStaticVars().
Member Function Documentation
tx_oop_Frontend_Template::__get ($ name)
Definition at line 89 of file Template.class.php.
tx_oop_Frontend_Template::__isset ($ name)
Definition at line 116 of file Template.class.php.
tx_oop_Frontend_Template::__set ($ name, $ value)
Definition at line 108 of file Template.class.php.
tx_oop_Frontend_Template::__toString ()
Definition at line 132 of file Template.class.php.
tx_oop_Frontend_Template::__unset ($ name)
Definition at line 124 of file Template.class.php.
tx_oop_Frontend_Template::_initTemplate ($ templateFilePath) [protected]
Loads a template file.
This function reads a template file and store it as a C-Object.
Parameters:
string The path of the template file to load
Returns:
NULL
Definition at line 200 of file Template.class.php.
Referenced by __construct().
static tx_oop_Frontend_Template::_setStaticVars () [static, private]
Definition at line 185 of file Template.class.php.
Referenced by __construct().
tx_oop_Frontend_Template::offsetExists ($ name)
Definition at line 169 of file Template.class.php.
tx_oop_Frontend_Template::offsetGet ($ name)
Definition at line 153 of file Template.class.php.
tx_oop_Frontend_Template::offsetSet ($ name, $ value)
Definition at line 161 of file Template.class.php.
tx_oop_Frontend_Template::offsetUnset ($ name)
Definition at line 177 of file Template.class.php.
Field Documentation
tx_oop_Frontend_Template::$_cObj = NULL [protected]
The instance of the tslib_cObj class.
Definition at line 53 of file Template.class.php.
tx_oop_Frontend_Template::$_hasStatic = false [static, private]
A flag to know wether the needed static variables are set.
Definition at line 43 of file Template.class.php.
tx_oop_Frontend_Template::$_sections = array() [protected]
The template sections.
Definition at line 63 of file Template.class.php.
tx_oop_Frontend_Template::$_str = NULL [static, protected]
The instance of the string utilities class (tx_oop_String_Utils).
Definition at line 48 of file Template.class.php.
tx_oop_Frontend_Template::$_templateContent = NULL [protected]
The template resource.
Definition at line 58 of file Template.class.php.
The documentation for this class was generated from the following file:
tx/oop/Frontend/Template.class.php