<?php
	/**
	 * Language labels for database tables/fields belonging to extension 'eesp_books'
	 *
	 * This file is detected by the translation tool.
	 */
	$LOCAL_LANG = Array (
		'default' => Array (
			'tt_content.list_type_pi1' => 'Liste des cahiers EESP',
			'tx_eespbooks_books' => 'Cahier EESP',
			'tx_eespbooks_books.s_product' => 'Produit',
			'tx_eespbooks_books.s_notice' => 'Notice',
			'tx_eespbooks_books.s_stock' => 'Stock',
			'tx_eespbooks_books.bookid' => 'ID / Numéro du livre',
			'tx_eespbooks_books.isbn' => 'ISBN / ISSN',
			'tx_eespbooks_books.pubyear' => 'Année',
			'tx_eespbooks_books.pubplace' => 'Lieu',
			'tx_eespbooks_books.pubmanagers' => 'Responsable(s) d\'édition',
			'tx_eespbooks_books.reedition' => 'Ré-édition',
			'tx_eespbooks_books.price_chf' => 'Prix (CHF - TTC)',
			'tx_eespbooks_books.price_eur' => 'Prix (EUR - HT)',
			'tx_eespbooks_books.pages' => 'Nombre de pages',
			'tx_eespbooks_books.format' => 'Format / Dimensions',
			'tx_eespbooks_books.physicaldetails' => 'Autres détails (reliure, etc)',
			'tx_eespbooks_books.copies' => 'Tirage initial',
			'tx_eespbooks_books.stock' => 'Etat du stock',
			'tx_eespbooks_books.flyers' => 'Nombre de flyers',
			'tx_eespbooks_books.pdf_locked' => 'PDF (verrouillé)',
			'tx_eespbooks_books.pdf_unlocked' => 'PDF (non verrouillé)',
			'tx_eespbooks_books.title' => 'Titre',
			'tx_eespbooks_books.subtitle' => 'Sous-titre',
			'tx_eespbooks_books.authors' => 'Auteur(s)',
			'tx_eespbooks_books.collection.I.0' => 'EESP',
			'tx_eespbooks_books.collection.I.1' => 'I.E.S',
			'tx_eespbooks_books.collection.I.2' => 'HEF',
			'tx_eespbooks_books.collection' => 'Collection',
			'tx_eespbooks_books.abstract' => 'Résumé',
			'tx_eespbooks_books.analysis' => 'Analyse',
			'tx_eespbooks_books.bibliography' => 'Bibliographie',
			'tx_eespbooks_books.cover' => 'Couverture',
			'tx_eespbooks_books.original' => 'Edition originale',
			'tx_eespbooks_stock' => 'Cahier EESP - Stock',
			'tx_eespbooks_stock.s_rel' => 'Relations',
			'tx_eespbooks_stock.s_sales' => 'Ventes',
			'tx_eespbooks_stock.s_students' => 'Etudiants',
			'tx_eespbooks_stock.s_events' => 'Manifestations',
			'tx_eespbooks_stock.s_send' => 'Envois',
			'tx_eespbooks_stock.s_back' => 'Retours',
			'tx_eespbooks_stock.s_misc' => 'Divers',
			'tx_eespbooks_stock.rel_book' => 'Cahier EESP',
			'tx_eespbooks_stock.rel_month' => 'Mois',
			'tx_eespbooks_stock.sales_reception' => 'Réception',
			'tx_eespbooks_stock.sales_bill' => 'Ventes par facture',
			'tx_eespbooks_stock.sales_free' => 'Distribution gratuite',
			'tx_eespbooks_stock.students_distribution' => 'Distribution',
			'tx_eespbooks_stock.students_exchange' => 'Echange',
			'tx_eespbooks_stock.events_out' => 'Sorties',
			'tx_eespbooks_stock.events_back' => 'Retours',
			'tx_eespbooks_stock.send_albert' => 'Albert le Grand',
			'tx_eespbooks_stock.send_cid' => 'CID',
			'tx_eespbooks_stock.back_students' => 'Etudiant',
			'tx_eespbooks_stock.back_cid' => 'CID',
			'tx_eespbooks_stock.comments' => 'Remarques',
			'tx_eespbooks_monthes' => 'Cahier EESP - Mois',
			'tx_eespbooks_monthes.stock_month' => 'Mois',
			'tx_eespbooks_monthes.stock_year' => 'Année',
		),
	);
?>
