<?php

########################################################################
# Extension Manager/Repository config file for ext: "cp_guide"
#
# Auto generated by Extbase Kickstarter 2010-03-30
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'CP / Guide',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Jean-David Gadina',
	'author_email' => 'macmade@netinfluence.com',
	'author_company' => 'netinfluence',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => 'mod1',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.2',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
