<?php
	/**
	 * Language labels for database tables / fields
	 * Belonging to extension "ergotheca"
	 *
	 * This file is detected by the translation tool
	 */
	$LOCAL_LANG = Array (
		"default" => Array (
			
			// Tools
			"tx_ergotheca_tools" => "Ergotheca tool",
			"tx_ergotheca_tools.fe_cruser_id" => "Frontend user",
			"tx_ergotheca_tools.name" => "Name",
			"tx_ergotheca_tools.authors" => "Authors",
			"tx_ergotheca_tools.testyear" => "Year",
			"tx_ergotheca_tools.evalfield.I.0" => "Physical health",
			"tx_ergotheca_tools.evalfield.I.1" => "Mental health",
			"tx_ergotheca_tools.evalfield.I.2" => "Community health",
			"tx_ergotheca_tools.evalfield" => "Evaluation field",
			"tx_ergotheca_tools.formalization.I.0" => "N/A",
			"tx_ergotheca_tools.formalization.I.1" => "Average",
			"tx_ergotheca_tools.formalization.I.2" => "Good",
			"tx_ergotheca_tools.formalization.I.3" => "Excellent",
			"tx_ergotheca_tools.formalization.I.4" => "Standard",
			"tx_ergotheca_tools.formalization" => "Formalization",
			"tx_ergotheca_tools.opencontent" => "Open Content",
			"tx_ergotheca_tools.evalobject" => "Evaluated object",
			"tx_ergotheca_tools.practicemodel" => "Model of practice",
			"tx_ergotheca_tools.targetpublic_age.I.0" => "Children (0-12)",
			"tx_ergotheca_tools.targetpublic_age.I.1" => "Teenager (13-16)",
			"tx_ergotheca_tools.targetpublic_age.I.2" => "Adult (-64)",
			"tx_ergotheca_tools.targetpublic_age.I.3" => "Elder people (65+)",
			"tx_ergotheca_tools.targetpublic_age" => "Target public / Age",
			"tx_ergotheca_tools.targetpublic_alt" => "Target public / Other",
			"tx_ergotheca_tools.bibliography" => "Bibliography",
			"tx_ergotheca_tools.keywords" => "Keywords",
			"tx_ergotheca_tools.passation_method.I.0" => "Auto evaluation",
			"tx_ergotheca_tools.passation_method.I.1" => "Hetero evaluation",
			"tx_ergotheca_tools.passation_method" => "Passation / Method",
			"tx_ergotheca_tools.passation_description" => "Passation / Description",
			"tx_ergotheca_tools.passation_procedure" => "Passation / Procedure",
			"tx_ergotheca_tools.passation_material" => "Passation / Material",
			"tx_ergotheca_tools.passation_setpos" => "Setting or position",
			"tx_ergotheca_tools.passation_quotint" => "Quotation and interpretation",
			"tx_ergotheca_tools.comments" => "Comments",
			"tx_ergotheca_tools.sources" => "Sources",
			"tx_ergotheca_tools.links" => "Links",
			"tx_ergotheca_tools.language.I.0" => "English",
			"tx_ergotheca_tools.language.I.1" => "French",
			"tx_ergotheca_tools.language.I.2" => "German",
			"tx_ergotheca_tools.language.I.3" => "Italian",
			"tx_ergotheca_tools.language.I.4" => "Spanish",
			"tx_ergotheca_tools.language.I.5" => "Other",
			"tx_ergotheca_tools.language" => "Original language",
			"tx_ergotheca_tools.language_alt" => "Original language / Other",
			"tx_ergotheca_tools.traduction.I.0" => "English",
			"tx_ergotheca_tools.traduction.I.1" => "French",
			"tx_ergotheca_tools.traduction.I.2" => "German",
			"tx_ergotheca_tools.traduction.I.3" => "Italian",
			"tx_ergotheca_tools.traduction.I.4" => "Spanish",
			"tx_ergotheca_tools.traduction" => "Traduction",
			"tx_ergotheca_tools.traduction_alt" => "Traduction / Other",
			"tx_ergotheca_tools.traduction_standard.I.0" => "English",
			"tx_ergotheca_tools.traduction_standard.I.1" => "French",
			"tx_ergotheca_tools.traduction_standard.I.2" => "German",
			"tx_ergotheca_tools.traduction_standard.I.3" => "Italian",
			"tx_ergotheca_tools.traduction_standard.I.4" => "Spanish",
			"tx_ergotheca_tools.traduction_standard" => "Standardized traduction",
			"tx_ergotheca_tools.traduction_standard_alt" => "Standardized traduction / Other",
			"tx_ergotheca_tools.eesp" => "EESP possession",
			"tx_ergotheca_tools.eesp_testyear" => "Test year",
			"tx_ergotheca_tools.usecond" => "Conditions of use",
			"tx_ergotheca_tools.remarks" => "Remarks",
			"tx_ergotheca_tools.cost" => "Cost",
			"tx_ergotheca_tools.pictures" => "Picture(s)",
			"tx_ergotheca_tools.files" => "File(s)",
			
			// Keywords
			"tx_ergotheca_keywords" => "Ergotheca keyword",
			"tx_ergotheca_keywords.keyword" => "Keyword",
			
			// Researches
			"tx_ergotheca_researches" => "Ergotheca research",
			"tx_ergotheca_researches.fe_cruser_id" => "Frontend user",
			"tx_ergotheca_researches.title" => "Title",
			"tx_ergotheca_researches.description" => "Description",
			"tx_ergotheca_researches.date_start" => "Start date",
			"tx_ergotheca_researches.date_end" => "End date",
			"tx_ergotheca_researches.tool" => "Related tool",
			
			// Plugins
			"tt_content.list_type_pi1" => "Ergotheca tools library",
			"tt_content.list_type_pi2" => "Ergotheca tools sharing",
			"tt_content.list_type_pi3" => "Ergotheca research",
		),
		"fr" => Array (
			
			// Tools
			"tx_ergotheca_tools" => "Outil Ergotheca",
			"tx_ergotheca_tools.fe_cruser_id" => "Utilisateur frontend",
			"tx_ergotheca_tools.name" => "Nom",
			"tx_ergotheca_tools.authors" => "Auteurs",
			"tx_ergotheca_tools.testyear" => "Année",
			"tx_ergotheca_tools.evalfield.I.0" => "Santé physique",
			"tx_ergotheca_tools.evalfield.I.1" => "Santé mentale",
			"tx_ergotheca_tools.evalfield.I.2" => "Santé communautaire",
			"tx_ergotheca_tools.evalfield" => "Champ d\'évaluation",
			"tx_ergotheca_tools.formalization.I.0" => "N/A",
			"tx_ergotheca_tools.formalization.I.1" => "Moyenne",
			"tx_ergotheca_tools.formalization.I.2" => "Bonne",
			"tx_ergotheca_tools.formalization.I.3" => "Excellent",
			"tx_ergotheca_tools.formalization.I.4" => "Standard",
			"tx_ergotheca_tools.formalization" => "Formalisation",
			"tx_ergotheca_tools.opencontent" => "Open Content",
			"tx_ergotheca_tools.evalobject" => "Objet évalué",
			"tx_ergotheca_tools.practicemodel" => "Modèle de pratique",
			"tx_ergotheca_tools.targetpublic_age.I.0" => "Enfant (0-12)",
			"tx_ergotheca_tools.targetpublic_age.I.1" => "Adolescent (13-16)",
			"tx_ergotheca_tools.targetpublic_age.I.2" => "Adulte (-64)",
			"tx_ergotheca_tools.targetpublic_age.I.3" => "Personne âgée (65+)",
			"tx_ergotheca_tools.targetpublic_age" => "Public cible / Age",
			"tx_ergotheca_tools.targetpublic_alt" => "Public cible / Autre",
			"tx_ergotheca_tools.bibliography" => "Bibliographie",
			"tx_ergotheca_tools.keywords" => "Mots clés",
			"tx_ergotheca_tools.passation_method.I.0" => "Auto-évaluation",
			"tx_ergotheca_tools.passation_method.I.1" => "Hétéro-évaluation",
			"tx_ergotheca_tools.passation_method" => "Passation / Méthode",
			"tx_ergotheca_tools.passation_description" => "Passation / Description",
			"tx_ergotheca_tools.passation_procedure" => "Passation / Procédure",
			"tx_ergotheca_tools.passation_material" => "Passation / Matériel",
			"tx_ergotheca_tools.passation_setpos" => "Setting ou position",
			"tx_ergotheca_tools.passation_quotint" => "Cotation et interptétation",
			"tx_ergotheca_tools.comments" => "Commentaires",
			"tx_ergotheca_tools.sources" => "Sources",
			"tx_ergotheca_tools.links" => "Liens",
			"tx_ergotheca_tools.language.I.0" => "Anglais",
			"tx_ergotheca_tools.language.I.1" => "Français",
			"tx_ergotheca_tools.language.I.2" => "Allemand",
			"tx_ergotheca_tools.language.I.3" => "Italien",
			"tx_ergotheca_tools.language.I.4" => "Espagnol",
			"tx_ergotheca_tools.language.I.5" => "Autre",
			"tx_ergotheca_tools.language" => "Langue originale",
			"tx_ergotheca_tools.language_alt" => "Langue originale / Autre",
			"tx_ergotheca_tools.traduction.I.0" => "Anglais",
			"tx_ergotheca_tools.traduction.I.1" => "Français",
			"tx_ergotheca_tools.traduction.I.2" => "Allemand",
			"tx_ergotheca_tools.traduction.I.3" => "Italien",
			"tx_ergotheca_tools.traduction.I.4" => "Espagnol",
			"tx_ergotheca_tools.traduction" => "Traduction",
			"tx_ergotheca_tools.traduction_alt" => "Traduction / Autre",
			"tx_ergotheca_tools.traduction_standard.I.0" => "Anglais",
			"tx_ergotheca_tools.traduction_standard.I.1" => "Français",
			"tx_ergotheca_tools.traduction_standard.I.2" => "Allemand",
			"tx_ergotheca_tools.traduction_standard.I.3" => "Italien",
			"tx_ergotheca_tools.traduction_standard.I.4" => "Espagnol",
			"tx_ergotheca_tools.traduction_standard" => "Traduction standardisée",
			"tx_ergotheca_tools.traduction_standard_alt" => "Traduction standardisée / Autre",
			"tx_ergotheca_tools.eesp" => "Possession EESP",
			"tx_ergotheca_tools.eesp_testyear" => "Année du test",
			"tx_ergotheca_tools.usecond" => "Conditions d\'utilisation",
			"tx_ergotheca_tools.remarks" => "Remarques",
			"tx_ergotheca_tools.cost" => "Coût",
			"tx_ergotheca_tools.pictures" => "Image(s)",
			"tx_ergotheca_tools.files" => "Fichier(s)",
			
			// Keywords
			"tx_ergotheca_keywords" => "Mot clé Ergotheca",
			"tx_ergotheca_keywords.keyword" => "Mot clé",
			
			// Researches
			"tx_ergotheca_researches" => "Recherche Ergotheca",
			"tx_ergotheca_researches.fe_cruser_id" => "Utilisateur frontend",
			"tx_ergotheca_researches.title" => "Titre",
			"tx_ergotheca_researches.description" => "Description",
			"tx_ergotheca_researches.date_start" => "Date de départ",
			"tx_ergotheca_researches.date_end" => "Date de fin",
			"tx_ergotheca_researches.tool" => "Outil associé",
			
			// Plugins
			"tt_content.list_type_pi1" => "Bibliothèque d'outils Ergotheca",
			"tt_content.list_type_pi2" => "Partage d'outils Ergotheca",
			"tt_content.list_type_pi3" => "Recherches Ergotheca",
		),
	);
?>
