<?php
	/**
	 * Language labels for database tables/fields belonging to extension "slideshow"
	 *
	 * This file is detected by the translation tool.
	 */
	$LOCAL_LANG = Array (
		'default' => Array (
			'tt_content.list_type_pi1' => 'Flash SlideShow',
			'tx_slideshow_slideshows' => 'Flash SlideShow',
			'tx_slideshow_slideshows.title' => 'Title',
			'tx_slideshow_slideshows.type' => 'Type',
			'tx_slideshow_slideshows.type.I.0' => 'Create each picture (default)',
			'tx_slideshow_slideshows.type.I.1' => 'Get pictures from a directory',
			'tx_slideshow_slideshows.file' => 'Pictures',
			'tx_slideshow_slideshows.pictures.section' => 'Add a JPG file',
			'tx_slideshow_slideshows.pictures.file' => 'File',
			'tx_slideshow_slideshows.pictures.path' => 'File path',
			'tx_slideshow_slideshows.pictures.link' => 'Link',
			'tx_slideshow_slideshows.pictures.link.I.0' => 'None',
			'tx_slideshow_slideshows.pictures.link.I.1' => 'External URL (use field below)',
			'tx_slideshow_slideshows.pictures.url' => 'External URL',
			'tx_slideshow_slideshows.dir_path' => 'Directory path (relative)',
			'tx_slideshow_slideshows.dir_pictures' => 'Select pictures',
			'tx_slideshow_slideshows.dir_url' => 'Optionnal URL for pictures',
			'tt_content.flexform_pi1.s_def' => 'Main',
			'tt_content.flexform_pi1.s_def.slideshow' => 'SlideShow',
			'tt_content.flexform_pi1.s_player' => 'Player settings',
			'tt_content.flexform_pi1.s_player.timer' => 'Timer (seconds)',
			'tt_content.flexform_pi1.s_player.random' => 'Random play',
			'tt_content.flexform_pi1.s_player.transition' => 'Transition',
			'tt_content.flexform_pi1.s_player.transition.I.0' => 'Blocks',
			'tt_content.flexform_pi1.s_player.transition.I.1' => 'Fade',
			'tt_content.flexform_pi1.s_player.transition.I.2' => 'Background fade',
			'tt_content.flexform_pi1.s_player.transition.I.3' => 'Circles',
			'tt_content.flexform_pi1.s_player.transition.I.4' => 'Fluids',
			'tt_content.flexform_pi1.s_player.navigation' => 'Show navigation',
			'tt_content.flexform_pi1.s_flash' => 'Flash settings',
			'tt_content.flexform_pi1.s_flash.version' => 'Version',
			'tt_content.flexform_pi1.s_flash.width' => 'Width',
			'tt_content.flexform_pi1.s_flash.height' => 'Height',
			'tt_content.flexform_pi1.s_flash.loop' => 'Loop',
			'tt_content.flexform_pi1.s_flash.menu' => 'Menu',
			'tt_content.flexform_pi1.s_flash.quality' => 'Quality',
			'tt_content.flexform_pi1.s_flash.scale' => 'Scale',
			'tt_content.flexform_pi1.s_flash.bgcolor' => 'BGColor',
			'tt_content.flexform_pi1.s_flash.bgcolor.wizard' => 'Color picker',
			'tt_content.flexform_pi1.s_flash.swliveconnect' => 'SWLiveConnect',
			'tt_content.flexform_pi1.LGL.default' => 'Default',
			'tt_content.flexform_pi1.LGL.no' => 'No',
			'tt_content.flexform_pi1.LGL.yes' => 'Yes',
		),
		'fr' => Array (
			'tt_content.list_type_pi1' => 'Présentation Flash',
			'tx_slideshow_slideshows' => 'Présentation Flash',
			'tx_slideshow_slideshows.title' => 'Titre',
			'tx_slideshow_slideshows.type' => 'Type',
			'tx_slideshow_slideshows.type.I.0' => 'Créer chaque image (par défaut)',
			'tx_slideshow_slideshows.type.I.1' => 'Obtenir les images depuis un répertoire',
			'tx_slideshow_slideshows.file' => 'Images',
			'tx_slideshow_slideshows.pictures.section' => 'Ajouter un fichier JPG',
			'tx_slideshow_slideshows.pictures.file' => 'Fichier',
			'tx_slideshow_slideshows.pictures.path' => 'Chemin du fichier',
			'tx_slideshow_slideshows.pictures.link' => 'Lien',
			'tx_slideshow_slideshows.pictures.link.I.0' => 'Aucun',
			'tx_slideshow_slideshows.pictures.link.I.1' => 'URL externe (utilisez le champ en dessous)',
			'tx_slideshow_slideshows.pictures.url' => 'URL externe',
			'tx_slideshow_slideshows.dir_path' => 'Chemin du répertoire (relatif)',
			'tx_slideshow_slideshows.dir_pictures' => 'Sélection des images',
			'tx_slideshow_slideshows.dir_url' => 'URL optionnel pour les images',
			'tt_content.flexform_pi1.s_def' => 'Général',
			'tt_content.flexform_pi1.s_def.slideshow' => 'Présentation',
			'tt_content.flexform_pi1.s_player' => 'Paramètres du lecteur',
			'tt_content.flexform_pi1.s_player.timer' => 'Temporisateur (secondes)',
			'tt_content.flexform_pi1.s_player.random' => 'Lecture aléatoire',
			'tt_content.flexform_pi1.s_player.transition' => 'Transition',
			'tt_content.flexform_pi1.s_player.transition.I.0' => 'Bloques',
			'tt_content.flexform_pi1.s_player.transition.I.1' => 'Fondu',
			'tt_content.flexform_pi1.s_player.transition.I.2' => 'Fondu avec le fond',
			'tt_content.flexform_pi1.s_player.transition.I.3' => 'Cercles',
			'tt_content.flexform_pi1.s_player.transition.I.4' => 'Fluide',
			'tt_content.flexform_pi1.s_player.navigation' => 'Afficher la navigation',
			'tt_content.flexform_pi1.s_flash' => 'Paramètres Flash',
			'tt_content.flexform_pi1.s_flash.version' => 'Version',
			'tt_content.flexform_pi1.s_flash.width' => 'Largeur',
			'tt_content.flexform_pi1.s_flash.height' => 'Hauteur',
			'tt_content.flexform_pi1.s_flash.loop' => 'Boucle',
			'tt_content.flexform_pi1.s_flash.menu' => 'Menu',
			'tt_content.flexform_pi1.s_flash.quality' => 'Qualité',
			'tt_content.flexform_pi1.s_flash.scale' => 'Redimensionnement',
			'tt_content.flexform_pi1.s_flash.bgcolor' => 'Couleur de fond',
			'tt_content.flexform_pi1.s_flash.bgcolor.wizard' => 'Sélecteur de couleurs',
			'tt_content.flexform_pi1.s_flash.swliveconnect' => 'SWLiveConnect',
			'tt_content.flexform_pi1.LGL.default' => 'Par défaut',
			'tt_content.flexform_pi1.LGL.no' => 'Non',
			'tt_content.flexform_pi1.LGL.yes' => 'Oui',
		),
	);
?>
